import type { Locale } from '@/lib/i18n';
const en = {
  details: 'Details', design: 'Design', proof: 'Print proof', saved: 'All changes saved', unsaved: 'Unsaved changes', saving: 'Saving…',
  discard: 'Discard changes', discardConfirm: 'Discard all changes since your last save?', save: 'Save changes', export: 'Review & print',
  format: 'Finished size', bleed: 'Bleed', bleedNone: 'No bleed', bleedThree: '3 mm on each edge', typography: 'Text size', language: 'Invitation language',
  production: 'Print setup', essentials: 'Names & venue', schedule: 'Schedule', wording: 'Message', visibility: 'Visible content',
  date: 'Event date', dateHint: 'The date comes from your event settings.', artworkWarning: 'This design uses low-resolution artwork. Request a proof from your printer before ordering; enlarging it does not add detail.',
  productionHint: 'Print at 100% / actual size, with backgrounds enabled and browser headers off. Confirm bleed and colour requirements with your printer.',
  bleedHint: 'Bleed extends the artwork beyond the cut line. Keep important text inside the inner guide. Guides do not print.',
  conflict: 'This invitation was changed elsewhere. Your edits are kept here. Reload to see the latest saved version before saving again.',
  failed: 'Could not save. Your edits are still here. Try again.', required: 'Enter both names before saving.',
  recovered: 'Unsaved work was found on this device.', restore: 'Restore edits', dismiss: 'Dismiss',
  preview: 'Preview', edit: 'Edit details', zoom: 'Photo zoom', horizontal: 'Horizontal position', vertical: 'Vertical position', reset: 'Reset crop', remove: 'Remove photo',
  cropHint: 'Drag to position your photo, or use the sliders.', photoHint: 'JPEG, PNG or WebP · up to 10 MB',
  uploadFail: 'Photo could not be uploaded. Your previous photo is unchanged. Try again.',
  loadFail: 'Photo could not be loaded. Retry before printing.', retry: 'Retry',
  overflow: 'Some text may extend outside the safe area or overlap. Shorten the text or reduce its size and review the proof.',
  photoResolution: 'This photo may be too small for sharp printing at this crop. Use a higher-resolution original.',
  readiness: 'Before you print', assetFail: 'An image or font could not load. Retry before printing.', preparing: 'Preparing print…',
  unsupported: 'Some saved details are not displayed by this design. They are kept when you switch designs.', digital: 'Digital RSVPs',
};
const hr: typeof en = {
  details: 'Detalji', design: 'Dizajn', proof: 'Probni otisak', saved: 'Sve promjene su spremljene', unsaved: 'Nespremljene promjene', saving: 'Spremanje…',
  discard: 'Odbaci promjene', discardConfirm: 'Odbaciti sve promjene od zadnjeg spremanja?', save: 'Spremi promjene', export: 'Pregled i ispis',
  format: 'Konačna veličina', bleed: 'Napust', bleedNone: 'Bez napusta', bleedThree: '3 mm sa svake strane', typography: 'Veličina teksta', language: 'Jezik pozivnice',
  production: 'Priprema za tisak', essentials: 'Imena i lokacija', schedule: 'Raspored', wording: 'Poruka', visibility: 'Vidljivi sadržaj',
  date: 'Datum događaja', dateHint: 'Datum se preuzima iz postavki događaja.', artworkWarning: 'Ovaj dizajn koristi ilustraciju niske rezolucije. Prije narudžbe zatražite probni otisak; povećavanje ne dodaje detalje.',
  productionHint: 'Ispišite u stvarnoj veličini (100%), s uključenim pozadinama i bez zaglavlja preglednika. Provjerite zahtjeve za napust i boje s tiskarom.',
  bleedHint: 'Napust proširuje ilustraciju izvan linije reza. Važan tekst zadržite unutar unutarnje vodilice. Vodilice se ne ispisuju.',
  conflict: 'Pozivnica je promijenjena drugdje. Vaše izmjene su sačuvane ovdje. Ponovno učitajte stranicu prije novog spremanja.',
  failed: 'Spremanje nije uspjelo. Vaše izmjene su još ovdje. Pokušajte ponovno.', required: 'Unesite oba imena prije spremanja.',
  recovered: 'Na ovom uređaju pronađene su nespremljene izmjene.', restore: 'Vrati izmjene', dismiss: 'Zanemari',
  preview: 'Pregled', edit: 'Uredi detalje', zoom: 'Povećanje fotografije', horizontal: 'Vodoravni položaj', vertical: 'Okomiti položaj', reset: 'Vrati izrez', remove: 'Ukloni fotografiju',
  cropHint: 'Povucite fotografiju ili koristite klizače za položaj.', photoHint: 'JPEG, PNG ili WebP · do 10 MB',
  uploadFail: 'Prijenos fotografije nije uspio. Prethodna fotografija nije promijenjena. Pokušajte ponovno.',
  loadFail: 'Fotografija se nije učitala. Pokušajte ponovno prije ispisa.', retry: 'Pokušaj ponovno',
  overflow: 'Dio teksta možda izlazi iz sigurnog područja ili se preklapa. Skratite tekst ili smanjite veličinu i provjerite pregled.',
  photoResolution: 'Fotografija je možda premala za oštar tisak pri ovom izrezu. Koristite izvornik veće rezolucije.',
  readiness: 'Prije ispisa', assetFail: 'Slika ili font nisu se učitali. Pokušajte ponovno prije ispisa.', preparing: 'Priprema ispisa…',
  unsupported: 'Ovaj dizajn ne prikazuje dio spremljenih detalja. Ostaju sačuvani za druge dizajne.', digital: 'Digitalni odgovori',
};
const de: typeof en = {
  details: 'Details', design: 'Design', proof: 'Druckvorschau', saved: 'Alle Änderungen gespeichert', unsaved: 'Ungespeicherte Änderungen', saving: 'Wird gespeichert…',
  discard: 'Änderungen verwerfen', discardConfirm: 'Alle Änderungen seit dem letzten Speichern verwerfen?', save: 'Änderungen speichern', export: 'Prüfen & drucken',
  format: 'Endformat', bleed: 'Beschnittzugabe', bleedNone: 'Ohne Beschnittzugabe', bleedThree: '3 mm an jeder Seite', typography: 'Textgröße', language: 'Sprache der Einladung',
  production: 'Druckeinstellungen', essentials: 'Namen & Veranstaltungsort', schedule: 'Ablauf', wording: 'Nachricht', visibility: 'Sichtbare Inhalte',
  date: 'Veranstaltungsdatum', dateHint: 'Das Datum stammt aus den Veranstaltungseinstellungen.', artworkWarning: 'Dieses Design verwendet niedrig aufgelöste Grafiken. Fordern Sie vor der Bestellung einen Probedruck an; Vergrößern fügt keine Details hinzu.',
  productionHint: 'Mit 100 % / tatsächlicher Größe, Hintergründen und ohne Browser-Kopfzeilen drucken. Beschnitt und Farbvorgaben mit der Druckerei abstimmen.',
  bleedHint: 'Der Beschnitt erweitert die Grafik über die Schnittkante. Wichtiger Text gehört innerhalb der inneren Hilfslinie. Hilfslinien werden nicht gedruckt.',
  conflict: 'Diese Einladung wurde anderswo geändert. Ihre Änderungen bleiben hier erhalten. Laden Sie die Seite vor dem erneuten Speichern neu.',
  failed: 'Speichern fehlgeschlagen. Ihre Änderungen sind noch vorhanden. Bitte erneut versuchen.', required: 'Bitte vor dem Speichern beide Namen eingeben.',
  recovered: 'Ungespeicherte Änderungen auf diesem Gerät gefunden.', restore: 'Änderungen wiederherstellen', dismiss: 'Schließen',
  preview: 'Vorschau', edit: 'Details bearbeiten', zoom: 'Fotozoom', horizontal: 'Horizontale Position', vertical: 'Vertikale Position', reset: 'Ausschnitt zurücksetzen', remove: 'Foto entfernen',
  cropHint: 'Foto ziehen oder mit den Reglern positionieren.', photoHint: 'JPEG, PNG oder WebP · bis 10 MB',
  uploadFail: 'Foto konnte nicht hochgeladen werden. Das vorherige Foto bleibt unverändert. Bitte erneut versuchen.',
  loadFail: 'Foto konnte nicht geladen werden. Vor dem Drucken erneut versuchen.', retry: 'Erneut versuchen',
  overflow: 'Text könnte außerhalb des Sicherheitsbereichs liegen oder überlappen. Text kürzen oder verkleinern und die Vorschau prüfen.',
  photoResolution: 'Dieses Foto könnte für einen scharfen Druck zu klein sein. Verwenden Sie ein höher aufgelöstes Original.',
  readiness: 'Vor dem Drucken', assetFail: 'Bild oder Schrift konnte nicht geladen werden. Vor dem Drucken erneut versuchen.', preparing: 'Druck wird vorbereitet…',
  unsupported: 'Dieses Design zeigt einige gespeicherte Details nicht an. Sie bleiben für andere Designs erhalten.', digital: 'Digitale Antworten',
};
export function invitationWorkspaceCopy(locale: Locale) { return locale === 'hr' ? hr : locale === 'de' ? de : en; }
