import type { AppUiDict } from "./en";

export const APP_UI_DE: AppUiDict = {
  defaults: {
    eventTitle: "Veranstaltung",
    organizer: "Organisator",
    guest: "Gast",
  },

  theme: {
    light: "hell",
    dark: "dunkel",
  },

  common: {
    cancel: "Abbrechen",
    delete: "Löschen",
    remove: "Entfernen",
    refresh: "Aktualisieren",
    copied: "Kopiert!",
    loading: "Laden …",
    working: "Wird ausgeführt …",
    back: "← Zurück",
    stay: "Bleiben",
    pending: "Ausstehend",
    errorFallback: "Fehler",
    configuringSupabase: "Konfiguriere Supabase für die Vorschau der Uploads.",
    loadCountsHint: "Konfiguriere Supabase, um aktuelle Zahlen zu laden.",
  },

  quotas: {
    unlimitedPlan: "Unbegrenzter Tarif",
    ofCount: "von {n}",
    notOnPlan: "In diesem Tarif nicht verfügbar",
  },

  plans: {
    free: "Kostenlos",
    standard: "Standard",
    plus: "Plus",
    premium: "Premium",
    max: "Max",
  },

  invites: {
    code: "Zugangscode",
    link: "Einladungslink",
    introShort: "Komm zur Veranstaltung:",
    introFriendly: "Du bist eingeladen zu",
    introFormal: "Du bist herzlich eingeladen zu",
    ctaShort: "Bis bald!",
    ctaFriendly: "Wir können es kaum erwarten!",
    ctaFormal: "Wir würden uns über deine Teilnahme sehr freuen.",
    templateShort: "Kurz",
    templateFriendly: "Locker",
    templateFormal: "Formal",
  },

  shell: {
    brand: "Calisto",
    navHome: "Start",
    navEvent: "Veranstaltung",
    navGallery: "Galerie",
    navGuests: "Gäste",
    navSettings: "Einstellungen",
    joinCta: "Mitmachen",
    newEventAria: "Neue Veranstaltung",
    newEventShort: "+",
    newEventLabel: "Neue Veranstaltung",
    eventBreadcrumb: "← Start",
    eventContext: "Veranstaltung",
  },

  accountMenu: {
    triggerSr: "Kontomenü",
    panelAria: "Konto",
    signedInLabel: "Angemeldet",
    profile: "Profil",
    settings: "Einstellungen",
    help: "Hilfe",
    themeLabel: "Design",
    signingOut: "Abmelden …",
    signOut: "Abmelden",
  },

  dashboard: {
    eyebrow: "Übersicht",
    helloTemplate: "Hallo, {name}",
    fallbackName: "Freund",
    subtitle: "Veranstaltungen, die du organisierst, als Co‑Organisator betreust oder als Gast beigetreten bist.",
    joinWithCode: "Mit Code mitmachen",
    createEvent: "Veranstaltung erstellen",
    yourEvents: "Deine Veranstaltungen",
    memberOne: "Mitglied",
    membersMany: "Mitglieder",
    roleOrganizer: "Organisator",
    roleCoOrganizer: "Co‑Organisator",
    roleGuest: "Gast",
    emptyHint: "Erstelle eine neue Veranstaltung oder tritt mit einem Code eines Organizers bei.",
    moreHint:
      "Erstelle noch eine Veranstaltung oder trete mit einem Code eines Organizers bei.",
    mostRecent: "Neuestes",
    earlierSeason: "Früher diese Saison",
    addAnother: "Oder ein weiteres",
    oneMoreHeading: "Noch eine auf dem Weg?",
  },

  joinEntryFooter: {
    howItWorks: "So funktioniert Calisto",
    home: "Start",
  },

  joinForm: {
    title: "Veranstaltung beitreten",
    subtitle: "Gib den Zugangscode ein, den dein Organisator teilt.",
    accessCodeLabel: "Zugangscode",
    hintFormats: "Hinweis: Codes sehen etwa so aus ",
    joinCta: "Mitmachen",
    codeTooShort: "Bitte den Code aus der Einladung eingeben (mindestens 4 Zeichen).",
    notFound:
      "Für diesen Code konnten wir keine Veranstaltung finden. Bitte prüfen und erneut versuchen.",
    genericError:
      "Beim Prüfen des Codes ist ein Fehler aufgetreten. Bitte erneut versuchen.",
    previewEyebrow: "Vorschau der Veranstaltung",
    codePrefix: "Code:",
    datePrefix: "Datum:",
    haveAccount: "Ich habe bereits ein Konto",
    guestContinue: "Als Gast fortfahren",
    changeCode: "Code ändern",
    scanQrInstead: "QR-Code scannen",
    scanInvalidQr: "Dieser QR-Code enthält keinen gültigen Beitrittslink oder Zugangscode.",
    scanQrTitle: "Einladungs-QR scannen",
    scanQrHint: "Nutze die Kamera, um den QR-Code von der Einladung oder dem Event-Poster zu scannen.",
    scanQrStartCamera: "Kamera starten",
    scanQrStopCamera: "Kamera stoppen",
    scanQrCamUnsupported: "Die Kamera konnte auf diesem Gerät nicht gestartet werden. Gib den Code manuell ein.",
    scanQrPermissionDenied:
      "Kamerazugriff wurde verweigert. Erlaube den Zugriff in den Browsereinstellungen oder gib den Code manuell ein.",
    scanQrNoCamera: "Keine nutzbare Kamera gefunden. Gib den Code stattdessen manuell ein.",
    scanEnterInstead: "Code eingeben",
  },

  globals: {
    errorTitle: "Etwas ist schiefgegangen",
    errorBody:
      "Es ist ein unerwarteter Fehler aufgetreten. Versuche es erneut oder kehre zur Startseite zurück.",
    tryAgain: "Erneut versuchen",
    home: "Start",
    notFoundCode: "404",
    notFoundTitle: "Seite nicht gefunden",
    notFoundBody: "Der Link ist möglicherweise defekt oder die Seite wurde verschoben.",
    calistoHome: "Calisto Start",
    welcomeLink: "Willkommen",
  },

  likes: {
    heartLikeAria: "Foto liken",
    heartUnlikeAria: "Like entfernen",
    likeCount: "{count} Likes",
    likersHeading: "Gefällt",
    likersEmpty: "Noch keine Likes",
    toggleFail: "Like konnte nicht aktualisiert werden. Bitte erneut versuchen.",
  },

  guestJoin: {
    loading: "Laden …",
    joining: "Beitritt zur Veranstaltung …",
    signedInNavAria: "Kontonavigation",
    myEvents: "Meine Veranstaltungen",
    manageEvent: "Veranstaltung verwalten",
    tagline: "Teile deine Erinnerungen an diese Veranstaltung.",
    uploadClosedBanner:
      "Uploads sind für diese Veranstaltung geschlossen (Zeitfenster beendet). Die Galerie bleibt sichtbar.",
    sectionUpload: "Upload",
    sectionGallery: "Galerie",
    joinInvalidOrNotFound:
      "Der Zugangscode ist für einen Beitritt gerade nicht gültig.",
    joinAlreadyMember: "Du gehörst bereits zu dieser Veranstaltung.",
    joinGeneric:
      "Beim Beitritt ist etwas schiefgelaufen. Bitte aktualisiere die Seite.",
  },

  welcomeModal: {
    eyebrow: "Du bist eingeladen",
    body: "Tritt bei, um Fotos und Videos hochzuladen und die Galerie zu sehen.",
    createAccount: "Konto erstellen",
    logIn: "Anmelden",
    continueGuest: "Als Gast fortfahren",
    nicknameLabel: "Dein Anzeigename",
    nicknamePlaceholder: "z. B. Ana",
    nicknameError: "Anzeigenamen zwischen 2 und 30 Zeichen.",
    supabaseMissing: "Supabase ist nicht konfiguriert. Versuche es später noch einmal.",
    enterGuest: "Als Gast eintreten",
    genericError: "Etwas ist schiefgegangen. Bitte erneut versuchen.",
  },

  upload: {
    closedEvent: "Uploads sind für diese Veranstaltung geschlossen.",
    quotaReached: "Das Foto-/Video‑Limit dieser Veranstaltung wurde erreicht.",
    needSignIn: "Melde dich an, um hochzuladen.",
    wrongType: "Nur Bilder und Videodateien werden unterstützt.",
    failedGeneric: "Upload fehlgeschlagen.",
    dropPrompt: "Fotos oder Videos hier ablegen",
    tapBrowse: "oder tippen zur Auswahl",
    uploading: "Wird hochgeladen …",
  },

  leaveRpc: {
    primaryOrganizer:
      "Primäre Organizer können hier nicht austreten – löschen Sie die Veranstaltung in den Einstellungen.",
    notMember: "Du gehörst nicht mehr zu dieser Veranstaltung.",
    notAuth: "Bitte melde dich erneut an, um fortzufahren.",
    fallback: "Austritt von der Veranstaltung nicht möglich.",
  },

  leave: {
    title: "Veranstaltung verlassen?",
    organizerMessage:
      "Du verlierst Zugang zu Upload und Freigaben. Bereits hochgeladene Medien bleiben in der Galerie für andere sichtbar.",
    guestMessage:
      "Du verlierst Zugriff auf dieses Album und Uploads. Bereits Hochgeladenes bleibt für andere Gäste.",
    confirm: "Verlassen",
    genericError: "Verlassen der Veranstaltung nicht möglich.",
    ctaOrganizerTab: "Veranstaltung verlassen",
    guestCtaSame: "Veranstaltung verlassen",
    cancelStay: "Bleiben",
  },

  auth: {
    oauthFail:
      "Google‑Anmeldung wurde nicht abgeschlossen. Bitte erneut versuchen oder E‑Mail und Passwort nutzen.",
    googleStartFail: "Google‑Anmeldung konnte nicht gestartet werden. Versuche es in Kürze erneut.",
    checkEmailVerify: "Öffne deine E‑Mails zur Kontobestätigung",
    welcomeEyebrow: "Willkommen bei",
    brandRest: ".",
    continueGoogle: "Mit Google fortfahren",
    dividerOr: "Oder",
    dividerBody: "mit E‑Mail fortfahren",
    email: "E‑Mail",
    password: "Passwort",
    signInSubmit: "Anmelden",
    forgotPw: "Passwort vergessen?",
    fullName: "Vollständiger Name",
    createAccountSubmit: "Konto anlegen",
    emailPlaceholderRegister: "du@beispiel.de",
    emailPlaceholderAlt: "du@beispiel.de",
    passwordDots: "••••••••",
    namePlaceholder: "Antonio Kovač",
    legalPrefix: "Mit Fortfahren stimmst du den Calisto",
    terms: "AGB",
    privacy: "Datenschutzrichtlinien",
    and: "und",
  },

  passwordReset: {
    forgotTitle: "Passwort vergessen",
    forgotSubtitle: "Gib deine E-Mail ein und wir senden dir einen Reset-Link.",
    emailRequired: "Bitte gib deine E-Mail-Adresse ein.",
    sendFail: "E-Mail konnte nicht gesendet werden. Bitte erneut versuchen.",
    sentMessage: "Prüfe deinen Posteingang — wir haben dir einen Link zum Zurücksetzen gesendet.",
    sendSubmit: "Link senden",
    backToSignIn: "Zurück zur Anmeldung",
    verifying: "Link wird überprüft…",
    expiredTitle: "Link abgelaufen",
    expiredBody: "Dieser Passwort-Reset-Link ist abgelaufen oder wurde bereits verwendet.",
    requestNewLink: "Neuen Link anfordern",
    accountEyebrow: "Dein Konto",
    setTitle: "Neues Passwort setzen",
    setSubtitle: "Wähle ein sicheres Passwort für dein Konto.",
    newPasswordLabel: "Neues Passwort",
    newPasswordPlaceholder: "••••••••",
    confirmPasswordLabel: "Passwort bestätigen",
    confirmPasswordPlaceholder: "••••••••",
    passwordTooShort: "Das Passwort muss mindestens 8 Zeichen lang sein.",
    passwordsMismatch: "Die Passwörter stimmen nicht überein.",
    updateFail: "Passwort konnte nicht aktualisiert werden. Bitte erneut versuchen.",
    updateSubmit: "Passwort aktualisieren",
    successTitle: "Passwort aktualisiert",
    successSubtitle: "Dein Passwort wurde erfolgreich geändert.",
    goToSignIn: "Zur Anmeldung",
  },

  authRail: {
    aria: "Anmeldung oder Registrierung auswählen",
    loginKicker: "Willkommen zurück",
    loginLabel: "Anmelden",
    registerKicker: "Neu bei Calisto?",
    registerLabel: "Registrieren",
  },

  forbidden: {
    title: "Veranstaltung nicht gefunden",
    deny: "Du hast keinen Zugang zu dieser Veranstaltung.",
    dashboardLink: "← Übersicht",
  },

  eventNav: {
    tabOverview: "Übersicht",
    tabGuests: "Gäste",
    tabGallery: "Galerie",
    tabShare: "Teilen",
    tabPrints: "Drucke",
    tabSettings: "Einstellungen",
    subtitle: "Teilen mit Gästen, damit diese beitreten können.",
    tabsAria: "Bereiche der Veranstaltung",
    myEvents: "Meine Veranstaltungen",
    memoriesCount: "{count} Erinnerungen",
    guestsCount: "{count} Gäste",
    bannerHint: "Ändere Banner-Stil und Emoji in den Einstellungen.",
  },

  printsTab: {
    kindEyebrow: "Drucke",
    kindTitle: "Um welche Art Veranstaltung handelt es sich?",
    kindHint: "Damit schlagen wir passende Einladungs- und Tischvorlagen vor.",
    kindOptionGeneric: "Allgemeine Veranstaltung",
    kindOptionWedding: "Hochzeit",
    confirmKindFail: "Speichern fehlgeschlagen. Bitte erneut versuchen.",
    title: "Drucke",
    subtitle: "Wähle ein Layout, ergänze deine Angaben und öffne die druckfertige Ansicht, wenn du soweit bist.",
    categoryInvitation: "Einladungen",
    eventDetails: "Veranstaltungsdetails",
    eventDetailsModalTitle: "Veranstaltungsdetails",
    eventDetailsClose: "Schließen",
    categoryTableQr: "Tisch & QR",
    templateTableMinimal: "Tischkarte · schlicht",
    templateTableBold: "Tischkarte · kräftig",
    templateWeddingInviteSimple: "Hochzeitseinladung · schlicht",
    templateWeddingInviteFloral: "Hochzeitseinladung · floral",
    templateWeddingInviteBlueFloral: "Hochzeitseinladung · blaues Blumendesign",
    templateWeddingInviteGeometric: "Hochzeitseinladung · geometrisch",
    templateWeddingInviteWatercolorCoast: "Hochzeitseinladung · Aquarell Küste",
    templateWeddingInviteNavyBotanical: "Hochzeitseinladung · dunkelblau floral",
    templateWeddingInviteGrayscaleGlitter: "Hochzeitseinladung · Graustufen & Gold",
    templateWeddingInviteTerraPill: "Hochzeitseinladung · Terrakotta & Blumen",
    templateWeddingInviteGoldArchFloral: "Hochzeitseinladung · Goldbogen floral",
    templateWeddingInviteCherryBlossom: "Hochzeitseinladung · Kirschblüten",
    templateWeddingInviteOliveGoldFrame: "Hochzeitseinladung · Olive & Goldrahmen",
    templateWeddingInviteGoldCirclesPhoto: "Hochzeitseinladung · Goldkreise & Foto",
    tableTemplateHint: "Öffnet eine druckfreundliche Seite mit Event‑QR und Beitrittsdetails.",
    invitationsComingSoon: "Demnächst",
    invitationsComingSoonHint: "Der Einladungsdruck kommt bald.",
    openPrintLayout: "Drucklayout öffnen",
    openPrintPreview: "Druckvorschau öffnen",
    inviteFieldPartnerA: "Name (erste Zeile)",
    inviteFieldPartnerB: "Name (zweite Zeile)",
    inviteFieldVenue: "Ort oder Adresse",
    inviteFieldVenueLineTwo: "Veranstaltungsadresse (optional)",
    inviteFieldExtraLine: "Uhrzeit oder Slogan (optional)",
    saveDraft: "Entwurf speichern",
    draftSaved: "Entwurf gespeichert.",
    draftSaveFail: "Entwurf konnte nicht gespeichert werden.",
    inviteCarouselPrev: "Vorheriges Design",
    inviteCarouselNext: "Nächstes Design",
    inviteCarouselSwipeHint: "Seitlich wischen, um Einladungsdesigns zu vergleichen",
    inviteCarouselCounter: "{current} von {total}",
    inviteFontScaleLabel: "Textgröße der Einladung",
    inviteFontScaleHint:
      "Nur Vorschau — beeinflusst den Druck nicht. So prüfen Sie, ob der Text auf dem Entwurf gut passt.",
    inviteAutoFitToggle: "Auto-fit",
    inviteAutoFitNotice: "Text automatisch an das Design angepasst",
    inviteAutoFitUndo: "Rückgängig",
    inviteFieldConnectorLabel: "Symbol zwischen den Namen",
    inviteFieldConnectorHeart: "♥",
    inviteFieldConnectorAmpersand: "&",
    inviteFieldConnectorInfinity: "∞",
    inviteFieldGatheringLabel: "Vorfeier",
    inviteFieldGatheringNone: "Keine",
    inviteFieldGatheringSame: "Gleicher Ort",
    inviteFieldGatheringSeparate: "Getrennte Orte",
    inviteFieldGatheringAddress: "Adresse",
    inviteFieldGatheringTime: "Uhrzeit",
    inviteFieldChurchLabel: "Kirche",
    inviteFieldChurchAddress: "Kirchenadresse",
    inviteFieldChurchTime: "Trauungsuhrzeit",
    inviteFieldDinnerLabel: "Empfang",
    inviteFieldDinnerAddress: "Empfangsadresse",
    inviteFieldDinnerTime: "Empfangsuhrzeit",
    inviteFieldQuoteLabel: "Zitat",
    inviteFieldQuoteText: "Zitattext",
    inviteFieldQuoteAuthor: "Zitatautor",
    inviteFieldVisibilityTitle: "Auf der Einladung anzeigen",
    inviteFieldVisibilityHint: "Zeilen für alle Designs ein- oder ausblenden. Ausgeblendete Felder bleiben gespeichert, erscheinen aber nicht im Druck.",
    inviteFieldVisibilityShow: "Anzeigen",
    inviteFieldVisibilityHide: "Ausblenden",
    inviteToggleTogetherFamilies: "Gemeinsam mit ihren Familien",
    inviteTogglePartnerNames: "Namen des Paares",
    inviteToggleInvitePreamble: "Einleitende Einladungszeilen",
    inviteToggleCordiallyInvite: "Herzliche Einladungszeile",
    inviteToggleWeddingTitle: "Titel „Hochzeit“",
    inviteToggleEventDate: "Datum der Trauung",
    inviteToggleExtraLine: "Uhrzeit / ausgeschriebenes Jahr",
    inviteToggleVenue: "Veranstaltungsort",
    inviteToggleVenueLineTwo: "Adresse des Ortes",
    inviteToggleReception: "Anschließendes Fest",
    inviteToggleGathering: "Treffen vor der Trauung",
    inviteToggleChurch: "Kirche / Zeremonie",
    inviteToggleDinner: "Abendessen / Empfang",
    inviteToggleQuote: "Zitat",
    comingSoonHeading: "Demnächst.",
    comingSoonDesc: "Eigene Einladungen, Programme und Erinnerungsstücke — hier gestalten und direkt bestellen.",
    comingSoonDesc2: "Wähle eine Vorlage, füll deine Eventdetails ein – den Rest übernehmen wir.",
    comingSoonBadge: "Wir arbeiten daran",
  },

  printsSetup: {
    emptyEyebrow: "Erstmalige Einrichtung",
    emptyHeading: "Lass uns deine Einladung gestalten.",
    emptySubhead: "Wir führen dich durch alle Details — Namen, Zeremonie, Empfang — damit deine Daten in jedes Design einfließen.",
    emptyCta: "Einrichtung starten",
    emptyMeta: "Dauert ca. 3 Minuten · Jederzeit pausierbar",
    stepCouple: "Das Paar",
    stepWhen: "Wann",
    stepGathering: "Empfang vorher",
    stepCeremony: "Zeremonie",
    stepReception: "Empfang",
    stepQuote: "Persönliche Note",
    stepReview: "Überprüfung",
    stepEyebrow: "Schritt {current} von {total}",
    coupleFirstName: "Erster Name",
    coupleSecondName: "Zweiter Name",
    coupleSymbol: "Symbol",
    symbolHeart: "Herz",
    symbolAnd: "Und",
    symbolInfinity: "Unendlich",
    whenDate: "Datum",
    whenTime: "Uhrzeit (optional)",
    gatheringNone: "Keiner",
    gatheringTogether: "Gleicher Ort",
    gatheringSeparate: "Getrennte Orte",
    gatheringAddress: "Adresse",
    gatheringTime: "Uhrzeit",
    ceremonyAddress: "Kirchenadresse",
    ceremonyTime: "Uhrzeit der Zeremonie",
    receptionVenue: "Empfangsort",
    receptionTime: "Empfangszeit",
    quoteLabel: "Zitat (optional)",
    quoteAuthor: "Zitatautor",
    reviewTitle: "Deine Einladung ist fertig.",
    reviewSubhead: "Überprüfe sie auf der rechten Seite, dann schalte die Druckdesigns frei.",
    reviewCouple: "Paar",
    reviewDate: "Datum",
    reviewGathering: "Empfang vorher",
    reviewCeremony: "Zeremonie",
    reviewReception: "Empfang",
    backToPrints: "Zurück zu Drucken",
    back: "Zurück",
    continue: "Weiter",
    finishSetup: "Einrichtung abschließen",
    livePreviewEyebrow: "Live-Vorschau",
    livePreviewSub: "Aktualisiert sich beim Tippen",
    editDetails: "Details bearbeiten",
    setupComplete: "Einrichtung abgeschlossen",
    setupCompleteHint: "Alle Einladungsdetails gespeichert. Jederzeit bearbeitbar.",
    saveFail: "Speichern fehlgeschlagen. Bitte erneut versuchen.",
  },

  overview: {
    yourRole: "Deine Rolle",
    uploadCloseLabel: "Verbleibende Zeit bis Ende der Uploads",
    uploadCloseShareHint: "Unter Teilen prüfen, ob Gäste heute noch hochladen können.",
    autoDeletionLabel: "Zeit bis zur automatischen Löschung des Events",
    autoDeletionOverdue: "Löschzeitpunkt überschritten — der nächste Purge‑Job entfernt dieses Event.",
    autoDeletionFooterHint:
      "Richtet sich nach deinem Tarif ab Veranstaltungsdatum. Änderungen an Datum oder Tarif aktualisieren das. Manuelles Löschen weiterhin unter Einstellungen.",
    countdownJoin: ", ",
    countdownDayOne: "{n} Tag",
    countdownDayMany: "{n} Tage",
    countdownHourOne: "{n} Stunde",
    countdownHourMany: "{n} Stunden",
    countdownMinuteOne: "{n} Minute",
    countdownMinuteMany: "{n} Minuten",
    countdownSubMinute: "Weniger als eine Minute",
    countdownMonthOne: "{n} Monat",
    countdownMonthMany: "{n} Monate",
    eventStartsIn: "Event startet in",
    uploadWindowEnded: "Upload‑Fenster beendet — Uploads sind geschlossen.",
    statsTitle: "Statistik",
    statsPhotos: "Fotos",
    statsVideos: "Videos",
    statsGuests: "Gäste",
    accessCodeTitle: "Zugangscode",
    copyCode: "Code kopieren",
    showQr: "QR‑Einladung anzeigen",
    hideQr: "QR ausblenden",
    scanHint: "Scan zum Beitreten · gleicher Link wie unter Teilen",
    openShareLink: "Zu Teilen für Link und Nachricht →",
    recentPhotos: "Neue Fotos",
    noPhotosHint:
      "Noch keine Uploads. Öffne die Galerie, sobald neue Medien eintreffen.",
    openGalleryBtn: "Zur Galerie",
    viewGalleryFull: "Vollständige Galerie →",
    planLabel: "Tarif",
    carouselLatest: "Neuestes",
    carouselMore: "+mehr",
    carouselLatestSix: "Die letzten sechs",
  },

  share: {
    heading: "Teilen",
    subtitle:
      "Sende Gastlink oder Zugangscode. Wähle den Nachrichtenstil, dann teilen oder kopieren.",
    messageStyleEyebrow: "Nachrichtsstil",
    shareInvite: "Einladung teilen",
    shareFootnote:
      "Nutzt das System‑Teilen, falls möglich, sonst wird die Nachricht kopiert.",
    shareInviteDialogTitle: "Du bist eingeladen",
    copyFailManual: "Kopieren fehlgeschlagen – Text bitte manuell auswählen.",
    shareUnavailable:
      "Teilen ist hier nicht möglich. Kopiere die Nachricht unten stattdessen.",
    scanQr: "QR scannen zum Beitreten",
    joinsSameHint: "Öffnet dieselbe Mitmach‑Seite wie der Link oben.",
    printPoster: "QR‑Plakat drucken",
    previewMessage: "Nachricht-Vorschau",
    copyFullMessage: "Nachricht kopieren",
    copyJoinLinkBtn: "Link kopieren",
  },

  gallery: {
    loadFailed: "Galerie konnte nicht geladen werden.",
    loading: "Galerie wird geladen …",
    deleteMediaFail: "Medien konnten nicht gelöscht werden.",
    deleteTitle: "Upload löschen?",
    deleteBody:
      "Entfernt den Eintrag und löscht die Datei. Das kann nicht rückgängig gemacht werden.",
    title: "Galerie",
    subtitle: "Hochgeladene Fotos & Videos durchsuchen",
    spotlightLabel: "Foto des Tages",
    addMemory: "Erinnerung hinzufügen",
    addMemoryHint: "Tippen zum Hochladen — oder Datei hier ablegen",
    memoriesCount: "{count} Erinnerungen",
    guestsCount: "{count} Gäste",
    filterAria: "Nach Medientyp filtern",
    filterAll: "Alle",
    filterPhotos: "Fotos",
    filterVideos: "Videos",
    empty: "Noch keine Uploads.",
    loadMore: "Mehr laden …",
    lightboxAria: "Foto‑Lightbox",
    closeLightboxAria: "Lightbox schließen",
    downloadPhotoAria: "Dieses Foto herunterladen",
    downloadBtn: "Herunterladen",
    downloadWorking: "Wird heruntergeladen …",
    downloadPhotoFail: "Download nicht möglich.",
    downloadFailedWithStatus: "Download fehlgeschlagen ({status}).",
    deleteBusy: "…",
    emptyGuest: "Noch keine Medien — lade als Erste:r hoch!",
    openPhotoAria: "Foto im Vollbild öffnen",
    uploadedByYouAria: "Dein Upload",
    zipExportCardEyebrow: "Primär‑Organisation",
    zipExportTitle: "ZIP‑Sammelexport",
    zipExportBlurb:
      "Medien der Galerie als ZIP laden. Wir bereiten das im Hintergrund vor und senden eine E‑Mail, sobald es fertig ist. Download‑Links laufen nach 24 Stunden ab.",
    zipExportPrepare: "ZIP vorbereiten",
    zipExportModalTitle: "Galerie‑ZIP vorbereiten",
    zipExportModalBody:
      "Fotos sind standardmäßig enthalten. Option aktivieren, um Videos einzubeziehen (größere Datei, längere Erstellung).",
    zipExportIncludeVideos: "Videos einbeziehen",
    zipExportStart: "Export starten",
    zipExportQueued: "In Warteschlange — wir melden uns, sobald es fertig ist.",
    zipExportRunning: "ZIP wird erstellt …",
    zipExportReady: "Bereit zum Download",
    zipExportFailed: "Export fehlgeschlagen",
    zipExportExpired: "Download abgelaufen",
    zipExportDownload: "ZIP herunterladen",
    zipExportErrorGeneric: "Export konnte nicht gestartet werden.",
    zipExportErrorPending: "Ein anderer Export läuft bereits.",
    zipExportErrorQueue:
      "Die Export‑Warteschlange konnte nicht gelesen werden. Bei eigenem Supabase‑Projekt die neuesten Migrationen anwenden (inkl. `media_zip_exports`). Sonst kurz warten und erneut versuchen.",
    zipExportErrorTooMany: "Zu viele Elemente für ein ZIP. Uploads reduzieren oder ohne Videos exportieren.",
    columnsLabel: "Spalten",
  },

  guests: {
    title: "Gäste",
    loadFailed: "Gäste konnten nicht geladen werden.",
    configureSupabase:
      "NEXT_PUBLIC_SUPABASE_URL und NEXT_PUBLIC_SUPABASE_ANON_KEY in `.env.local` setzen, um Organizer‑Features zu nutzen.",
    cannotRemoveOrganizer:
      "Der primäre Organisator kann nicht entfernt werden.",
    rolesOnlyPrimary:
      "Nur der primäre Organisator kann Rollen ändern.",
    notAllowed: "Nicht erlaubt.",
    memberNotFound: "Mitglied nicht gefunden.",
    actionFailed: "Aktion fehlgeschlagen.",
    removeMemberFail: "Mitglied konnte nicht entfernt werden.",
    updateRoleFail: "Rolle konnte nicht geändert werden.",
    removeDialogTitle: "Dieses Mitglied entfernen?",
    removeDialogBody:
      "Verliert Zugang zu Veranstaltung und Galerie. Hochgeladene Medien bleiben bis zum Löschen in der Galerie.",
    loadingGuests: "Gäste werden geladen …",
    empty: "Noch keine Gäste.",
    youBadge: "(du)",
    uploadsLine: "Uploads: {photos} Fotos • {videos} Videos",
    promoteCo: "Zum Co‑Organisator machen",
    demoteGuest: "Zum Gast machen",
    guestLabelFallback: "Gast",
    organizerLabelFallback: "Organisator",
    membersOne: "1 Mitglied",
    membersMany: "{n} Mitglieder",
  },

  supabase: {
    missingTitle: "Supabase nicht konfiguriert",
    settingsBody:
      "NEXT_PUBLIC_SUPABASE_URL und NEXT_PUBLIC_SUPABASE_ANON_KEY in `.env.local` setzen, um Einstellungen zu bearbeiten.",
    galleryBody:
      "NEXT_PUBLIC_SUPABASE_URL und NEXT_PUBLIC_SUPABASE_ANON_KEY in `.env.local` setzen, um die Galerie zu laden.",
  },

  settingsPage: {
    title: "Einstellungen",
    eventsLink: "Veranstaltungen",
  },

  settingsClient: {
    profileEyebrow: "Profil",
    signedInAs: "Angemeldet als ",
    anon: "—",
    appearanceEyebrow: "Aussehen",
    languageEyebrow: "Sprache",
    langEnglish: "Englisch",
    langHrvatski: "Kroatisch",
    langDeutsch: "Deutsch",
    themeDarkLabel: "Dunkel",
    themeLightLabel: "Hell",
    appliesNote: "Wirkt auf Seiten mit hellem oder dunklem Design.",
    signOut: "Abmelden",
    backEvents: "← Zurück zu Veranstaltungen",
    uploadNameEyebrow: "Uploads & Galerie",
    uploadNameLabel: "Name bei deinen Uploads",
    uploadNameHint:
      "Wird neben deinen Fotos und Videos in Veranstaltungs‑Galerien angezeigt. Nutzt dein Profil; Galerie nach dem Speichern aktualisieren.",
    uploadNamePlaceholder: "z. B. Alex",
    saveUploadName: "Namen speichern",
    uploadNameSaved: "Gespeichert.",
    uploadNameSaveFail: "Speichern fehlgeschlagen. Bitte erneut versuchen.",
    uploadNameNotSignedIn: "Nicht angemeldet.",
  },

  settingsTab: {
    heading: "Einstellungen",
    subtitle:
      "Nur du (primärer Organisator) siehst diesen Bereich und wie die Veranstaltung wirkt.",
    sectionNameIcon: "Name & Symbol",
    eventNameLabel: "Name der Veranstaltung",
    namePlaceholder: "z. B. Anna & Luca",
    iconEyebrow: "Symbolemoji",
    chooseEmoji: "Emoji wählen",
    closePicker: "Schließen",
    noIcon: "Kein Symbol",
    emojiAria: "Ausgewähltes Emoji",
    emojiPickerAria: "Emoji‑Auswahl",
    iconHint:
      "Zeigt sich neben dem Titel im Header. Ohne Emoji wird nur in der Navigation ein Standard angezeigt.",
    saveChanges: "Speichern",
    reset: "Zurücksetzen",
    sectionSchedule: "Veranstaltungsdetails",
    scheduleNoteLead: "Gespeichert als ",
    scheduleNoteTrail:
      "(Kalenderdatum). Datum oder Tarif wirken sich auf Gast‑Zeitfenster und Medien‑Limits aus.",
    eventDateUtc: "Datum (Kalendertag, UTC)",
    planTier: "Tarif",
    saveSchedule: "Datum & Tarif speichern",
    joinCodeEyebrow: "Einladungs‑Code für Gäste",
    dashboardBack: "Zur Übersicht",
    dangerEyebrow: "Gefahrenbereich",
    deletePhraseWord: "DELETE",
    confirmMismatch:
      "Die Bestätigung passt nicht. Bitte gespeicherten Titel genau angeben oder DELETE schreiben.",
    deleteStorageIncomplete:
      "Veranstaltung entfernt, aber einzelne Speicher‑Dateien fehlen möglicherweise noch. Kontaktiere den Support.",
    deleteFail: "Löschen nicht möglich.",
    genericSaveFail: "Speichern nicht möglich.",
    validDateNeeded: "Bitte ein gültiges Datum wählen.",
    scheduleSaveFail: "Datum oder Tarif konnte nicht aktualisiert werden.",
    dateLockNotice: "Das Event hat bereits begonnen — das Datum ist gesperrt, um eine Verlängerung der Upload- oder Löschfenster zu verhindern.",
    deleteTitleForever: "Veranstaltung dauerhaft löschen?",
    deleteDialogBody:
      "Allen entfällt sofort der Zugang. Gäste, Galerie, Uploads und Codes verschwinden.",
    deleteConfirmLabel: "Ja, endgültig löschen",
    deleteDangerNote: "Das kann nicht rückgängig gemacht werden.",
    deleteInstructionLead: "Tippe zur Bestätigung entweder den gespeicherten Titel ",
    deleteInstructionTrail: " oder das Wort ",
    deleteConfirmPhraseLabel: "Bestätigung",
    deletePlaceholderTitleOrWord: "Titel oder DELETE",
    deleteButton: "Veranstaltung komplett löschen",
    exactParen: "(exakt)",
  },

  validateCreate: {
    nameRequired:
      "Ein Veranstaltungsname wird benötigt. Bitte zurück und einen Namen eintragen.",
  },

  createStep1: {
    eyebrow: "Neue Veranstaltung",
    title: "Veranstaltung erstellen",
    description: "Du wirst automatisch Organisator.",
    eventTitleLabel: "Veranstaltungstitel",
    namePlaceholder: "z. B. Anna & Luca",
    eventIconEyebrow: "Symbol",
    eventDateLabel: "Datum der Veranstaltung",
    continuePlan: "Weiter zum Tarif →",
    searchEmojiHint: "Alle Emojis durchsuchen. Es erscheint im Veranstaltungs‑Header.",
    noEmojiBtn: "Ohne Emoji",
    defaultEmojiAria: "Ausgewähltes Emoji",
  },

  createStep2: {
    eyebrow: "Schritt 2 von 3",
    heading: "Tarif wählen",
    description: "Wähle einen Tarif, der zur Veranstaltung passt.",
    priceEyebrow: "Preis",
    sale: "Aktion",
    popularBadge: "Beliebt",
    unlimited: "Unbegrenzt",
    guestsPhotosVideos: "{guests} Gäste • {photos} Fotos • {videos} Videos",
    uploadsOpenAfterDays:
      "{n} Tage Upload nach dem Veranstaltungsdatum",
    moreDetailsAria: "Mehr Infos zum Tarif {plan}",
    detailRegionAria: "Details zum Tarif {plan}",
    rowGuests: "Gäste",
    rowPhotos: "Fotos",
    rowVideos: "Videos",
    rowUploadWindow: "Upload‑Fenster",
    uploadWindowDays: "{n} Tage",
    tipChangePlanLater:
      "Hinweis: Du kannst den Tarif später in den Veranstaltungs‑Einstellungen ändern.",
    continuePayment: "Weiter zur Zahlung →",
    payWord: "Zahlung",
    planWord: "Tarif",
    dayWord: "Tag",
    daysWord: "Tage",
  },

  createStep3: {
    validationBack: "Zurück zu den Details",
    checkingSession: "Sitzung wird geprüft …",
    needAuthHeading: "Melde dich an, um fertigzustellen",
    needAuthBody:
      "Du brauchst ein Konto, um die Erstellung zu beenden. Dein Entwurf bleibt erhalten.",
    logInBtn: "Anmelden",
    createAcctBtn: "Konto anlegen",
    checkoutFailGeneric: "Checkout konnte nicht gestartet werden.",
    createFail: "Veranstaltung konnte nicht erstellt werden.",
    stepEyebrow: "Schritt 3 · Prüfen & erstellen",
    confirmHeading: "Veranstaltung bestätigen",
    confirmBodyLeadBeforeName: "Du erstellst jetzt ",
    confirmBodyBetweenNameDate: " am ",
    confirmBodyTierWord: " mit dem ",
    confirmBodyPlanSuffix: "‑Tarif",
    confirmBodyPaidTail:
      " Die Zahlung läuft sicher über Stripe, danach ist die Veranstaltung mit den Tarifs‑Limits aktiv.",
    confirmBodyFreeTier:
      "Die kostenlose Stufe wird hier ohne Checkout bestätigt – lade gleich Gäste ein.",
    selectedPlanEyebrow: "Gewählter Tarif",
    saleBadge: "Angebot",
    priceNotePaid:
      "Inkl. Mehrwertsteuer wenn anwendbar — einmalig bei Bestätigung in Stripe.",
    priceNoteFree: "Kostenlos bleibt kostenlos.",
    footnotePaid: "Du gehst zu Stripe; nach erfolgreicher Zahlung ist alles aktiv.",
    footnoteFree:
      "Keine Gebühr — Album und Gästeinladung sind sofort online.",
    btnOpeningCheckout: "Checkout wird geöffnet …",
    btnCreating: "Wird erstellt …",
    btnStripe: "Weiter zu Stripe",
    btnConfirmFree: "Bestätigen und erstellen",
  },

  stripeComplete: {
    missingSession: "Checkout‑Session fehlt.",
    fulfillFailGeneric: "Checkout konnte nicht abgeschlossen werden.",
    fulfillRetryHint:
      "Wenn die Zahlung gerade durchgelaufen ist, kurz warten und „Erneut versuchen“ nutzen.",
    noEventId: "Zahlung abgeschlossen, aber keine Veranstaltungs‑ID zurückgegeben.",
    tryAgain: "Erneut versuchen",
    goDashboard: "Zur Übersicht",
    finalizing:
      "Zahlung wird abgeschlossen und Veranstaltung angelegt …",
  },

  onboardingForm: {
    welcomeEyebrow: "Willkommen",
    title: "Erzähl uns von deinem Event",
    subtitle:
      "So personalisiert sich dein Platz. Als Nächstes kannst du in der Übersicht dein erstes Event erstellen.",
    kindEyebrow: "Was planst du?",
    displayNameLabel: "Wie sollen wir dich nennen? (optional)",
    namePlaceholderShort: "z. B. Alex",
    choosePlanning: "Bitte wähle eine Art Veranstaltung.",
    saveFail: "Speichern fehlgeschlagen. Versuche es erneut.",
    notSignedIn: "Nicht angemeldet.",
    continueDashboard: "Weiter zur Übersicht",
  },

  onboardingKinds: {
    wedding: "Hochzeit",
    birthday: "Geburtstag",
    corporate: "Firmlich",
    other: "Etwas anderes",
  },

  planTiersPage: {
    eyebrow: "Tarife",
    title: "Tarifstufen",
    subtitle: "Kurzüberblick über Gäste- und Upload‑Limits.",
    back: "Zurück",
    uploadBadge: "{n} Tage Upload",
    colGuests: "Gäste",
    colPhotos: "Fotos",
    colVideos: "Videos",
  },

  print: {
    deniedTitle: "Veranstaltung nicht gefunden",
    deniedDeny: "Du hast keinen Zugang zu dieser Veranstaltung.",
    backDashboard: "← Übersicht",
    backShare: "← Zurück zu Teilen",
    print: "Drucken",
    heroEyebrow: "QR scannen zum Hochladen von Fotos und Videos",
    footerGoToLead: "Oder öffne ",
    footerGoToTrail: " und gib ein:",
    sheetHelper:
      "Zwei identische Tischkarten pro Blatt. Entlang der gestrichelten Linie schneiden und je eine Karte auf einen Tisch legen.",
    cutHere: "Hier schneiden",
    downloadPdf: "PDF herunterladen",
    changeTheme: "Design ändern",
    previewPdf: "Vorschau",
    paperSectionLabel: "Papierformat",
    printThemeLabel: "Thema",
    printSheetChip: "2 Karten pro {paper}-Blatt · in der Mitte schneiden",
    paperA4: "A4",
    paperLetter: "US Letter",
    templateSectionLabel: "Layout",
    templateTableMinimal: "Reduziert",
    templateTableBold: "Kräftig",
    templateQrClean: "Schlicht",
    templateQrGold: "Gold",
    templateQrDark: "Dunkel",
    templateQrSimple: "Schlicht",
    templateQrRomantic: "Romantisch",
    templateQrLuxurious: "Luxuriös",
    templateQrBotanical: "Botanisch",
    templateQrArtDeco: "Art Deco",
    templateQrPlayful: "Verspielt",
    templateQrCelestial: "Celestial",
    templateQrCoastal: "Küste",
    templateQrBoho: "Boho",
    templateQrNoir: "Noir",
    templateQrWatercolor: "Aquarell",
    templateQrRetro: "Retro",
    templateQrTropical: "Tropisch",
    templateQrScandi: "Skandinavisch",
    templateQrSunset: "Sonnenuntergang",
    templateQrRustic: "Rustikal",
    qrCardSimpleTagline: "SCANNEN & BEITRETEN",
    qrCardSimpleHeadline: "Teile den Moment.",
    qrCardSimpleBody: "Richte die Kamera auf den Code und füge deine Fotos direkt in unser gemeinsames Album ein.",
    qrCardRomanticTagline: "Mit Freude vereint",
    qrCardRomanticBody: "Scan, um deine Fotos zu teilen und jeden zärtlichen Moment mit uns zu erleben.",
    qrCardRomanticCta: "scan mich",
    qrCardLuxuriousBody: "Ein Abend, den man nicht vergisst. Scan und füge deine Fotos unserer privaten Galerie hinzu.",
    qrCardBotanicalTagline: "Zusammen erblühen",
    qrCardBotanicalBody: "Hilf unserem Erinnerungsgarten zu wachsen — scan und füge deine Aufnahmen von heute hinzu.",
    qrCardArtDecoBody: "Eine glamouröse Nacht erwartet dich. Scan und teile die Magie.",
    qrCardPlayfulBadge: "Auf geht's",
    qrCardPlayfulHeadline: "Knips es. Teile es!",
    qrCardPlayfulBody: "Scan den Code und wirf dein Foto ins gemeinsame Party-Album.",
    qrCardCelestialTagline: "Unter den Sternen",
    qrCardCelestialBody: "Fange die Magie dieser Nacht ein — scan und teile deine Fotos mit uns.",
    qrCardCoastalTagline: "Am Meer",
    qrCardCoastalBody: "Lass die Erinnerungswelle rollen — scan und füge deine Fotos dem Album hinzu.",
    qrCardBohoTagline: "Wild & frei",
    qrCardBohoBody: "Komm zusammen und teile die Momente, die du heute festhältst.",
    qrCardNoirSub: "SCAN · TEILE · ERLEBE",
    qrCardNoirHeadline: "TEILE DIE NACHT",
    qrCardNoirBody: "Richte die Kamera auf den Code und füge Fotos unserem gemeinsamen Album hinzu.",
    qrCardWatercolorTagline: "Ein Tag zum Erinnern",
    qrCardWatercolorBody: "Bemale unser Album mit deinen Farben — scan und teile die Momente.",
    qrCardRetroBadge: "Nur gute Vibes",
    qrCardRetroBody: "Scan und wirf deine besten Aufnahmen ins gemeinsame Album.",
    qrCardTropicalTagline: "Aloha & feiern",
    qrCardTropicalBody: "Genieß die Sonne und teile deine Schnappschüsse — scan für unser Album.",
    qrCardScandiTagline: "Hej & willkommen",
    qrCardScandiBody: "Scan den Code und füge deine Fotos direkt unserem gemeinsamen Album hinzu.",
    qrCardSunsetTagline: "Goldene Stunde",
    qrCardSunsetBody: "Jage das Licht mit uns — scan und teile jedes Foto des Abends.",
    qrCardRusticTagline: "Bewahre unsere Erinnerungen",
    qrCardRusticBody: "Scan und füge die Fotos, die du aufnimmst, unserem gemeinsamen Album hinzu.",
    templateWeddingInviteSimple: "Hochzeit · schlicht",
    templateWeddingInviteFloral: "Hochzeit · floral",
    templateWeddingInviteBlueFloral: "Hochzeit · blaues Blumendesign",
    templateWeddingInviteGeometric: "Hochzeit · geometrisch",
    templateWeddingInviteWatercolorCoast: "Hochzeit · Aquarell Küste",
    templateWeddingInviteNavyBotanical: "Hochzeit · dunkelblau floral",
    templateWeddingInviteGrayscaleGlitter: "Hochzeit · Graustufen & Gold",
    templateWeddingInviteTerraPill: "Hochzeit · Terrakotta & Blumen",
    templateWeddingInviteGoldArchFloral: "Hochzeit · Goldbogen floral",
    templateWeddingInviteCherryBlossom: "Hochzeit · Kirschblüten",
    templateWeddingInviteOliveGoldFrame: "Hochzeit · Olive & Gold",
    templateWeddingInviteGoldCirclesPhoto: "Hochzeit · Goldkreise & Foto",
    inviteGoldCirclesYoureInvited: "Sie sind eingeladen zur Hochzeit von",
    inviteGoldCirclesUploadPhoto: "Foto hochladen",
    inviteGoldCirclesChangePhoto: "Foto ändern",
    inviteGoldCirclesUploading: "Wird hochgeladen…",
    inviteGoldCirclesUploadError: "Upload fehlgeschlagen. Erneut versuchen.",
    inviteTogetherWithOurFamilies: "GEMEINSAM MIT UNSEREN FAMILIEN",
    inviteHonorUniteMarriage:
      "wir erbitten höflich die Ehre Ihrer Anwesenheit, wenn wir unsere Leben in der Ehe vereinen",
    inviteGlitterCordiallyLine: "Sie sind herzlich eingeladen zur",
    inviteGlitterWeddingOfLine: "Hochzeit von",
    inviteGlitterTogetherFamilies: "Gemeinsam mit ihren Familien",
    inviteGlitterCordiallyInviteCaps: "laden Sie herzlich ein zu ihrer",
    inviteGlitterWeddingWord: "Hochzeit",
    inviteGlitterOn: "am",
    inviteTerraPleaseJoinUsFor: "Wir laden Sie herzlich ein zu",
    inviteWatercolorPleaseJoinUs: "Bitte nehmen Sie teil",
    inviteWatercolorForCeremony: "an unserer Hochzeitszeremonie",
    inviteTerraTheWeddingOf: "der Hochzeit von",
    inviteGoldArchHeadline: "Wir laden Sie herzlich zur Hochzeit ein",
    inviteCherryPreambleStart: "Sie sind herzlich",
    inviteCherryPreambleScript: "eingeladen",
    inviteCherryPreambleMid: "zur",
    inviteCherryPreambleEnd: "Hochzeit von",
    inviteOliveWithLove: "mit Liebe",
    inviteOliveCordiallyLine1: "wir laden Sie herzlich ein",
    inviteOliveCordiallyLine2: "zu unserer Trauung",
    inviteCategoryLabel: "Einladungen",
    tableCategoryLabel: "Tischkarten",
    inviteTogetherWithFamilies: "GEMEINSAM MIT IHREN FAMILIEN",
    inviteCelebrationOn: "LADEN SIE EIN, IHRE HOCHZEITSFEIER MITZUFEIERN AM",
    inviteReceptionFollow: "Anschließendes Fest",
    inviteWithJoyYouAre: "mit Freude laden ein",
    inviteInvitedToWeddingOf: "zur Hochzeit von",
    inviteAnd: "und",
    inviteDetailsGathering: "Treffen",
    inviteDetailsChurch: "Trauung",
    inviteDetailsDinner: "Feier",
    sheetHelperInvitation: "Hochformat‑Vorschau der Einladung. Das Papierformat gilt weiterhin beim Drucken.",
    backPrints: "← Zurück zu Drucke",
    invitationUnavailableTitle: "Dieses Layout ist nicht verfügbar",
    invitationUnavailable: "Dieses Einladungslayout ist für diese Veranstaltungsart nicht verfügbar.",
    posterLanguageLabel: "Sprache auf dem Plakat",
  },

  languagePicker: {
    label: "Sprache",
    locales: {
      en: "Englisch",
      hr: "Kroatisch",
      de: "Deutsch",
    },
  },
};
