/** English UI strings — source shape for HR/DE packs. Do not use `as const` so locale packs widen to compatible `string`. */
export const APP_UI_EN = {
  defaults: {
    eventTitle: "Event",
    organizer: "Organizer",
    guest: "Guest",
  },

  theme: {
    light: "light",
    dark: "dark",
  },

  common: {
    cancel: "Cancel",
    delete: "Delete",
    remove: "Remove",
    refresh: "Refresh",
    copied: "Copied!",
    loading: "Loading…",
    working: "Working…",
    back: "← Back",
    stay: "Stay",
    pending: "Pending",
    errorFallback: "Error",
    configuringSupabase: "Configure Supabase to preview uploads.",
    loadCountsHint: "Configure Supabase to load live counts.",
  },

  quotas: {
    unlimitedPlan: "Unlimited plan",
    ofCount: "of {n}",
    notOnPlan: "Not on this plan",
  },

  plans: {
    free: "Free",
    standard: "Standard",
    plus: "Plus",
    premium: "Premium",
    max: "Max",
  },

  invites: {
    code: "Access code",
    link: "Join link",
    introShort: "Join our event:",
    introFriendly: "You're invited to",
    introFormal: "You are cordially invited to",
    ctaShort: "Hope to see you there!",
    ctaFriendly: "Can't wait to celebrate with you!",
    ctaFormal: "We would be honored by your presence.",
    templateShort: "Short",
    templateFriendly: "Friendly",
    templateFormal: "Formal",
  },

  shell: {
    brand: "Calisto",
    navHome: "Home",
    navSettings: "Settings",
    joinCta: "Join",
    newEventAria: "New event",
    newEventShort: "+",
    newEventLabel: "+ New Event",
    eventBreadcrumb: "← Home",
    eventContext: "Event",
  },

  accountMenu: {
    triggerSr: "Account menu",
    panelAria: "Account",
    signedInLabel: "Signed in",
    profile: "Profile",
    settings: "Settings",
    help: "Help",
    themeLabel: "Theme",
    signingOut: "Signing out…",
    signOut: "Sign out",
  },

  dashboard: {
    eyebrow: "Dashboard",
    helloTemplate: "Hello, {name}",
    fallbackName: "friend",
    subtitle: "Events you organise, co‑organise, or joined as a guest.",
    joinWithCode: "Join with code",
    createEvent: "+ Create event",
    yourEvents: "Your events",
    memberOne: "member",
    membersMany: "members",
    roleOrganizer: "Organizer",
    roleCoOrganizer: "Co-organizer",
    roleGuest: "Guest",
    emptyHint: "Create a new event or join an existing one with a code from your organizer.",
    moreHint: "Create another event or join one with a code from your organizer.",
  },

  joinEntryFooter: {
    howItWorks: "How Calisto works",
    home: "Home",
  },

  joinForm: {
    title: "Join Event",
    subtitle: "Enter the access code shared by your event organizer.",
    accessCodeLabel: "Access Code",
    hintFormats: 'Hint: codes look like ',
    joinCta: "Join Event →",
    codeTooShort: "Enter the code from your invite (at least 4 characters).",
    notFound: "We could not find an event for that code. Please check and try again.",
    genericError: "Something went wrong while checking your code. Please try again.",
    previewEyebrow: "Event Preview",
    codePrefix: "Code:",
    datePrefix: "Date:",
    haveAccount: "I have an account",
    guestContinue: "Continue as guest",
    changeCode: "Change code",
    scanQrInstead: "Scan QR code",
    scanInvalidQr: "That QR code doesn’t contain a valid join link or access code.",
    scanQrTitle: "Scan invite QR",
    scanQrHint: "Use your camera to scan the QR from your invite or event poster.",
    scanQrStartCamera: "Start camera",
    scanQrStopCamera: "Stop camera",
    scanQrCamUnsupported: "We couldn’t start the camera on this device. Try entering the code manually.",
    scanQrPermissionDenied:
      "Camera permission was denied. Allow camera access in your browser settings, or enter the code manually.",
    scanQrNoCamera: "No usable camera was found. Enter the code manually instead.",
    scanEnterInstead: "Enter code instead",
  },

  globals: {
    errorTitle: "Something went wrong",
    errorBody: "An unexpected error occurred. You can retry, or return to the homepage.",
    tryAgain: "Try again",
    home: "Home",
    notFoundCode: "404",
    notFoundTitle: "Page not found",
    notFoundBody: "The link may be broken or the page may have moved.",
    calistoHome: "Calisto home",
    welcomeLink: "Welcome",
  },

  likes: {
    heartLikeAria: "Like this photo",
    heartUnlikeAria: "Unlike this photo",
    likeCount: "{count} likes",
    likersHeading: "Liked by",
    likersEmpty: "No likes yet",
    toggleFail: "Could not update like. Please try again.",
  },

  guestJoin: {
    loading: "Loading…",
    joining: "Joining event…",
    signedInNavAria: "Account navigation",
    myEvents: "My events",
    manageEvent: "Manage event",
    tagline: "Share your memories from this event.",
    uploadClosedBanner:
      "Uploads are closed for this event (upload window ended). You can still browse the gallery.",
    sectionUpload: "Upload",
    sectionGallery: "Gallery",
    joinInvalidOrNotFound: "That access code isn’t valid for joining right now.",
    joinAlreadyMember: "You’re already part of this event.",
    joinGeneric: "Something went wrong while joining. Try refreshing the page.",
  },

  welcomeModal: {
    eyebrow: "You're invited",
    body: "Join to upload photos & videos and browse the gallery.",
    createAccount: "Create account",
    logIn: "Log in",
    continueGuest: "Continue as guest",
    nicknameLabel: "Your nickname",
    nicknameError: "Nickname must be 2–30 characters.",
    supabaseMissing: "Supabase is not configured. Please try again later.",
    enterGuest: "Enter as guest",
    genericError: "Something went wrong. Please try again.",
  },

  upload: {
    closedEvent: "Uploads are closed for this event.",
    quotaReached: "This event has reached its photo or video limit.",
    needSignIn: "Please sign in to upload.",
    wrongType: "Only image and video files are supported.",
    failedGeneric: "Upload failed.",
    dropPrompt: "Drag & drop photos or videos here",
    tapBrowse: "or tap to browse",
    uploading: "Uploading…",
  },

  leaveRpc: {
    primaryOrganizer: "The primary organizer can’t leave this way — delete the event in Settings instead.",
    notMember: "You’re not a member of this event anymore.",
    notAuth: "Sign in again to continue.",
    fallback: "Could not leave this event.",
  },

  leave: {
    title: "Leave this event?",
    organizerMessage:
      "You will lose access to uploads and sharing for this event. Photos and videos you already uploaded stay in the gallery for everyone else.",
    guestMessage:
      "You will lose access to this album and uploads. Anything you’ve already uploaded stays in the gallery for other guests.",
    confirm: "Leave event",
    genericError: "Could not leave this event.",
    ctaOrganizerTab: "Leave event",
    guestCtaSame: "Leave event",
    cancelStay: "Stay",
  },

  auth: {
    oauthFail: "Google sign-in didn’t finish. Try again or use email and password.",
    googleStartFail: "Could not start Google sign-in. Try again shortly.",
    checkEmailVerify: "Check your email to confirm your account",
    welcomeEyebrow: "Welcome to",
    brandRest: ".",
    continueGoogle: "Continue with Google",
    dividerOr: "Or",
    dividerBody: "continue with email",
    email: "Email",
    password: "Password",
    signInSubmit: "Sign In",
    forgotPw: "Forgot password?",
    fullName: "Full name",
    createAccountSubmit: "Create Account",
    emailPlaceholderRegister: "you@example.com",
    emailPlaceholderAlt: "you@example.com",
    passwordDots: "••••••••",
    namePlaceholder: "Antonio Kovač",
    legalPrefix: "By continuing you agree to Calisto's",
    terms: "Terms",
    privacy: "Privacy Policy",
    and: "and",
  },

  authRail: {
    aria: "Choose sign in or register",
    loginKicker: "Welcome back",
    loginLabel: "Sign in",
    registerKicker: "New to Calisto",
    registerLabel: "Register",
  },

  forbidden: {
    title: "Event not found",
    deny: "You don't have access to this event.",
    dashboardLink: "← Dashboard",
  },

  eventNav: {
    tabOverview: "Overview",
    tabGuests: "Guests",
    tabGallery: "Gallery",
    tabShare: "Share",
    tabSettings: "Settings",
    subtitle: "Share with guests to let them join.",
    tabsAria: "Event sections",
  },

  overview: {
    yourRole: "Your role",
    uploadCloseLabel: "Time until uploads close",
    uploadCloseShareHint: "See Share for whether guests can upload today.",
    autoDeletionLabel: "Time until automatic event deletion",
    autoDeletionOverdue: "Removal time passed — the next purge job will delete this event.",
    autoDeletionFooterHint:
      "Based on your plan tier from the event date. Changing date or plan updates this. You can still delete manually in Settings.",
    countdownJoin: ", ",
    countdownDayOne: "{n} day",
    countdownDayMany: "{n} days",
    countdownHourOne: "{n} hour",
    countdownHourMany: "{n} hours",
    countdownMinuteOne: "{n} minute",
    countdownMinuteMany: "{n} minutes",
    countdownSubMinute: "Less than a minute",
    uploadWindowEnded: "Upload window ended — uploads are closed.",
    statsTitle: "Statistics",
    statsPhotos: "Photos",
    statsVideos: "Videos",
    statsGuests: "Guests",
    accessCodeTitle: "Access Code",
    copyCode: "Copy code",
    showQr: "Show QR Invite",
    hideQr: "Hide QR",
    scanHint: "Scan to join · same link as the Share tab",
    openShareLink: "Open Share for link & message →",
    recentPhotos: "Recent photos",
    noPhotosHint: "No uploads yet. Open the gallery to see guest photos and videos when they arrive.",
    openGalleryBtn: "Go to Gallery",
    viewGalleryFull: "View full gallery →",
  },

  share: {
    heading: "Share",
    subtitle: "Send a guest link or access code. Pick a message style, then share or copy.",
    messageStyleEyebrow: "Message style",
    shareInvite: "Share invite",
    shareFootnote:
      "Uses your device share sheet when available; otherwise copies the full message.",
    shareInviteDialogTitle: "You're invited",
    copyFailManual: "Could not copy — try selecting the text manually.",
    shareUnavailable: "Sharing isn't available in this browser. Copy the message below instead.",
    scanQr: "Scan to join",
    joinsSameHint: "Opens the same join page as the link above.",
    printPoster: "Print QR poster",
    previewMessage: "Preview message",
    copyFullMessage: "Copy full message",
    copyJoinLinkBtn: "Copy link",
  },

  gallery: {
    loadFailed: "Failed to load gallery.",
    loading: "Loading gallery…",
    deleteMediaFail: "Could not delete media.",
    deleteTitle: "Delete this upload?",
    deleteBody: "This removes the item from your gallery and deletes the stored file. This cannot be undone.",
    title: "Gallery",
    subtitle: "Browse uploaded photos & videos",
    filterAria: "Filter by media type",
    filterAll: "All",
    filterPhotos: "Photos",
    filterVideos: "Videos",
    empty: "No uploads yet.",
    loadMore: "Load more…",
    lightboxAria: "Photo lightbox",
    closeLightboxAria: "Close lightbox",
    downloadPhotoAria: "Download this photo",
    downloadBtn: "Download",
    downloadWorking: "Downloading…",
    downloadPhotoFail: "Could not download this photo.",
    downloadFailedWithStatus: "Download failed ({status}).",
    deleteBusy: "…",
    emptyGuest: "No media yet — be the first to upload!",
    openPhotoAria: "Open photo full screen",
    zipExportCardEyebrow: "Primary organizer",
    zipExportTitle: "Bulk ZIP export",
    zipExportBlurb:
      "Download gallery media in one ZIP. We prepare it in the background and email you when it is ready. Download links expire after 24 hours.",
    zipExportPrepare: "Prepare ZIP",
    zipExportModalTitle: "Prepare gallery ZIP",
    zipExportModalBody:
      "Photos are included by default. Turn on the option below to include videos (larger file, longer build).",
    zipExportIncludeVideos: "Include videos",
    zipExportStart: "Start export",
    zipExportQueued: "Queued — we will notify you when it is ready.",
    zipExportRunning: "Building your ZIP…",
    zipExportReady: "Ready to download",
    zipExportFailed: "Export failed",
    zipExportExpired: "Download expired",
    zipExportDownload: "Download ZIP",
    zipExportErrorGeneric: "Could not start export.",
    zipExportErrorPending: "Another export is already in progress.",
    zipExportErrorQueue:
      "The export queue could not be read. If you use your own Supabase project, apply the latest migrations (including `media_zip_exports`). Otherwise try again in a moment.",
    zipExportErrorTooMany: "Too many items for one ZIP. Remove some uploads or export without videos.",
  },

  guests: {
    title: "Guests",
    loadFailed: "Failed to load guests.",
    configureSupabase:
      "Set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY in `.env.local` to use event admin features.",
    cannotRemoveOrganizer: "You can't remove the primary organizer.",
    rolesOnlyPrimary: "Only the primary organizer can change roles.",
    notAllowed: "Not allowed.",
    memberNotFound: "Member not found.",
    actionFailed: "Action failed.",
    removeMemberFail: "Could not remove member.",
    updateRoleFail: "Could not update role.",
    removeDialogTitle: "Remove this member?",
    removeDialogBody:
      "They will lose access to this event and its gallery. Uploaded media stays unless you delete it from the gallery.",
    loadingGuests: "Loading guests…",
    empty: "No guests have joined yet.",
    youBadge: "(you)",
    uploadsLine: "Uploads: {photos} photos • {videos} videos",
    promoteCo: "Promote to co‑organizer",
    demoteGuest: "Demote to guest",
    guestLabelFallback: "Guest",
    organizerLabelFallback: "Organizer",
    membersOne: "1 member",
    membersMany: "{n} members",
  },

  supabase: {
    missingTitle: "Supabase not configured",
    settingsBody:
      "Set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY in `.env.local` to edit event settings.",
    galleryBody:
      "Set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY in `.env.local` to load the gallery.",
  },

  settingsPage: {
    title: "Settings",
    eventsLink: "Events",
  },

  settingsClient: {
    profileEyebrow: "Profile",
    signedInAs: "Signed in as ",
    anon: "—",
    appearanceEyebrow: "Appearance",
    languageEyebrow: "Language",
    langEnglish: "English",
    langHrvatski: "Hrvatski",
    langDeutsch: "Deutsch",
    themeDarkLabel: "Dark",
    themeLightLabel: "Light",
    appliesNote: "Applies to pages that support light and dark.",
    signOut: "Sign out",
    backEvents: "← Back to events",
    uploadNameEyebrow: "Uploads & gallery",
    uploadNameLabel: "Name on your uploads",
    uploadNameHint:
      "Shown next to photos and videos you add in event galleries. Uses your profile; refresh the gallery after saving.",
    uploadNamePlaceholder: "e.g. Alex",
    saveUploadName: "Save name",
    uploadNameSaved: "Saved.",
    uploadNameSaveFail: "Could not save. Try again.",
    uploadNameNotSignedIn: "Not signed in.",
  },

  settingsTab: {
    heading: "Settings",
    subtitle: "Only you (the primary organizer) see this tab — update how this event appears in Calisto.",
    sectionNameIcon: "Name & icon",
    eventNameLabel: "Event name",
    namePlaceholder: "e.g. Kyle & Laura",
    iconEyebrow: "Event icon",
    chooseEmoji: "Choose emoji",
    closePicker: "Close picker",
    noIcon: "No icon",
    emojiAria: "Selected emoji",
    emojiPickerAria: "Emoji picker",
    iconHint:
      "Shown next to your event title in the header. If you skip an icon, a default is used in the nav only.",
    saveChanges: "Save changes",
    reset: "Reset",
    sectionSchedule: "Event details",
    scheduleNoteLead: "Saved as ",
    scheduleNoteTrail:
      "(calendar). Changing the date or plan updates guest upload windows and media limits for this event — in-app checkout for paid tiers is not live yet.",
    eventDateUtc: "Event date (UTC calendar day)",
    planTier: "Plan tier",
    saveSchedule: "Save date & plan",
    joinCodeEyebrow: "Guest join code",
    dashboardBack: "Back to dashboard",
    dangerEyebrow: "Danger zone",
    deletePhraseWord: "DELETE",
    confirmMismatch: "Confirmation didn’t match. Enter the saved event title exactly, or type DELETE.",
    deleteStorageIncomplete: "The event was removed but some files couldn’t be deleted from storage. Contact support.",
    deleteFail: "Could not delete this event.",
    genericSaveFail: "Could not save changes.",
    validDateNeeded: "Choose a valid event date.",
    scheduleSaveFail: "Could not update date or plan.",
    deleteTitleForever: "Delete event forever?",
    deleteDialogBody:
      "Everyone loses access immediately. Guests, gallery files, uploads, invite codes — all removed.",
    deleteConfirmLabel: "Yes, delete permanently",
    deleteDangerNote: "Permanent deletion cannot be undone.",
    deleteInstructionLead: "Confirm by typing either the saved event title ",
    deleteInstructionTrail: "exactly as stored, or the word ",
    deleteConfirmPhraseLabel: "Confirmation",
    deletePlaceholderTitleOrWord: "Title or DELETE",
    deleteButton: "Delete this event completely",
    exactParen: "(exact)",
  },

  validateCreate: {
    nameRequired: "Event name is required. Please go back and enter a name.",
  },

  createStep1: {
    eyebrow: "New event",
    title: "Create event",
    description: "You'll automatically become the organizer.",
    eventTitleLabel: "Event title",
    namePlaceholder: "e.g. Kyle & Laura",
    eventIconEyebrow: "Event icon",
    eventDateLabel: "Event date",
    continuePlan: "Continue to plan →",
    searchEmojiHint: "Search or browse all emojis. Your choice appears in the event header.",
    noEmojiBtn: "No emoji",
    defaultEmojiAria: "Selected emoji",
  },

  createStep2: {
    eyebrow: "Step 2 of 3",
    heading: "Choose a plan",
    description: "Select the plan that fits your event size.",
    priceEyebrow: "Price",
    sale: "Sale",
    popularBadge: "Popular",
    unlimited: "Unlimited",
    guestsPhotosVideos: "{guests} guests • {photos} photos • {videos} videos",
    uploadsOpenAfterDays: "Uploads open for {n} days after the event",
    moreDetailsAria: "More details about the {plan} plan",
    detailRegionAria: "{plan} plan details",
    rowGuests: "Guests",
    rowPhotos: "Photos",
    rowVideos: "Videos",
    rowUploadWindow: "Upload window",
    uploadWindowDays: "{n} days",
    tipChangePlanLater: "Tip: You can change plans later from your event settings.",
    continuePayment: "Continue to payment →",
    payWord: "payment",
    planWord: "plan",
    dayWord: "day",
    daysWord: "days",
  },

  createStep3: {
    validationBack: "Go back to details",
    checkingSession: "Checking your session…",
    needAuthHeading: "Sign in to create your event",
    needAuthBody:
      "You need an account to finish creating this event. We'll keep your draft so you can continue on return.",
    logInBtn: "Log in",
    createAcctBtn: "Create account",
    checkoutFailGeneric: "Could not start checkout.",
    createFail: "Could not create event.",
    stepEyebrow: "Step 3 · Review & create",
    confirmHeading: "Confirm your event",
    confirmBodyLeadBeforeName: "You’re about to create ",
    confirmBodyBetweenNameDate: " on ",
    confirmBodyTierWord: " on the ",
    confirmBodyPlanSuffix: " tier",
    confirmBodyPaidTail:
      " You'll confirm payment securely with Stripe, then your event opens with the tier's limits.",
    confirmBodyFreeTier:
      "The free tier is confirmed here with no checkout — invite guests right away.",
    selectedPlanEyebrow: "Selected plan",
    saleBadge: "Sale",
    priceNotePaid: "Price includes VAT where applicable — charged once when you confirm in Stripe.",
    priceNoteFree: "Free tier stays free.",
    footnotePaid: "You’ll jump to Stripe to pay; when it succeeds your event opens right away.",
    footnoteFree: "No charge — your album and invite code go live immediately.",
    btnOpeningCheckout: "Opening checkout…",
    btnCreating: "Creating…",
    btnStripe: "Continue to Stripe",
    btnConfirmFree: "Confirm and create event",
  },

  stripeComplete: {
    missingSession: "Missing checkout session.",
    fulfillFailGeneric: "Could not finish checkout.",
    fulfillRetryHint: 'If payment just finished, wait a moment and use "Try again".',
    noEventId: "Checkout finished but event id was not returned.",
    tryAgain: "Try again",
    goDashboard: "Go to dashboard",
    finalizing: "Finalizing payment and creating your event…",
  },

  onboardingForm: {
    welcomeEyebrow: "Welcome",
    title: "Tell us about your event",
    subtitle: "This personalizes your space. You can create your first event from the dashboard next.",
    kindEyebrow: "What are you planning?",
    displayNameLabel: "What should we call you? (optional)",
    namePlaceholderShort: "e.g. Alex",
    choosePlanning: "Choose what you're planning.",
    saveFail: "Could not save. Try again.",
    notSignedIn: "Not signed in.",
    continueDashboard: "Continue to dashboard",
  },

  onboardingKinds: {
    wedding: "Wedding",
    birthday: "Birthday",
    corporate: "Corporate",
    other: "Something else",
  },

  planTiersPage: {
    eyebrow: "Plans",
    title: "Plan tiers",
    subtitle: "A quick summary of guest and upload limits.",
    back: "Back",
    uploadBadge: "{n} days uploads",
    colGuests: "Guests",
    colPhotos: "Photos",
    colVideos: "Videos",
  },

  print: {
    deniedTitle: "Event not found",
    deniedDeny: "You don't have access to this event.",
    backDashboard: "← Dashboard",
    backShare: "← Back to Share",
    print: "Print",
    heroEyebrow: "Scan to upload photos & videos",
    footerGoToLead: "Or go to ",
    footerGoToTrail: " and enter code:",
    sheetHelper:
      "Two identical table cards per sheet. Cut along the dashed line to place one card on each table.",
    cutHere: "Cut here",
    paperSectionLabel: "Paper size",
    paperA4: "A4",
    paperLetter: "US Letter",
    templateSectionLabel: "Layout",
    templateTableMinimal: "Minimal",
    templateTableBold: "Bold",
    posterLanguageLabel: "Poster language",
  },

  languagePicker: {
    label: "Language",
    locales: {
      en: "English",
      hr: "Croatian",
      de: "German",
    },
  },
};

export type AppUiDict = typeof APP_UI_EN;
