/** English UI strings — source shape for HR/DE packs. Do not use `as const` so locale packs widen to compatible `string`. */
export const APP_UI_EN = {
  defaults: {
    eventTitle: "Event",
    organizer: "Organizer",
    guest: "Guest",
  },

  theme: {
    light: "light",
    dark: "dark",
  },

  common: {
    cancel: "Cancel",
    delete: "Delete",
    remove: "Remove",
    refresh: "Refresh",
    copied: "Copied!",
    loading: "Loading…",
    working: "Working…",
    back: "← Back",
    stay: "Stay",
    pending: "Pending",
    errorFallback: "Error",
    configuringSupabase: "Configure Supabase to preview uploads.",
    loadCountsHint: "Configure Supabase to load live counts.",
  },

  quotas: {
    unlimitedPlan: "Unlimited plan",
    ofCount: "of {n}",
    notOnPlan: "Not on this plan",
  },

  plans: {
    free: "Free",
    standard: "Standard",
    plus: "Plus",
    premium: "Premium",
    max: "Max",
  },

  upgrade: {
    bannerEyebrow: "Upgrade",
    bannerTitle: "Get more from your event",
    bannerBody:
      "You're on the Free plan. Upgrade any time for more guests and photos, videos, and a longer time before your event is deleted.",
    bannerCta: "See upgrade plans",
    settingsCta: "Upgrade plan",
    pickerTitle: "Choose a plan",
    pickerSubtitle: "One time payment, no subscription. Pick the plan that fits your event.",
    oneTimeNote: "One time payment. Your access code and everything you've set up stays the same.",
    guestsPhotosVideos: "{guests} guests · {photos} photos · {videos} videos",
    retentionDays: "Kept for {n} days after the event",
    selectCta: "Upgrade to {plan}",
    cancel: "Not now",
    opening: "Opening checkout…",
    errorGeneric: "Could not start checkout. Please try again.",
    finalizingTitle: "Finalizing your upgrade…",
    finalizingBody: "This can take a few seconds after payment. Hang tight.",
    successTitle: "Upgrade complete",
    successBody: "Your event is now on the {plan} plan.",
    successDismiss: "Done",
  },

  invites: {
    code: "Access code",
    link: "Join link",
    introShort: "Join our event:",
    introFriendly: "You're invited to",
    introFormal: "You are cordially invited to",
    ctaShort: "Hope to see you there!",
    ctaFriendly: "Can't wait to celebrate with you!",
    ctaFormal: "We would be honored by your presence.",
    templateShort: "Short",
    templateFriendly: "Friendly",
    templateFormal: "Formal",
  },

  shell: {
    brand: "Calisto",
    navHome: "Home",
    navEvent: "Event",
    navGallery: "Gallery",
    navGuests: "Guests",
    navSettings: "Settings",
    joinCta: "Join",
    newEventAria: "New event",
    newEventShort: "+",
    newEventLabel: "New Event",
    eventBreadcrumb: "← Home",
    eventContext: "Event",
  },

  accountMenu: {
    triggerSr: "Account menu",
    panelAria: "Account",
    signedInLabel: "Signed in",
    profile: "Profile",
    settings: "Settings",
    help: "Help",
    themeLabel: "Theme",
    signingOut: "Signing out…",
    signOut: "Sign out",
  },

  dashboard: {
    eyebrow: "Dashboard",
    helloTemplate: "Hello, {name}",
    fallbackName: "friend",
    subtitle: "Events you organise, co‑organise, or joined as a guest.",
    joinWithCode: "Join with code",
    createEvent: "Create event",
    yourEvents: "Your events",
    memberOne: "member",
    membersMany: "members",
    roleOrganizer: "Organizer",
    roleCoOrganizer: "Co-organizer",
    roleGuest: "Guest",
    emptyHint: "Create a new event or join an existing one with a code from your organizer.",
    moreHint: "Create another event or join one with a code from your organizer.",
    mostRecent: "Most recent",
    earlierSeason: "Earlier this season",
    addAnother: "Or add another",
    oneMoreHeading: "One more on the way?",
  },

  joinEntryFooter: {
    howItWorks: "How Calisto works",
    home: "Home",
  },

  joinForm: {
    title: "Join Event",
    subtitle: "Enter the access code shared by your event organizer.",
    accessCodeLabel: "Access Code",
    hintFormats: 'Hint: codes look like ',
    joinCta: "Join Event",
    codeTooShort: "Enter the code from your invite (at least 4 characters).",
    notFound: "We could not find an event for that code. Please check and try again.",
    genericError: "Something went wrong while checking your code. Please try again.",
    previewEyebrow: "Event Preview",
    codePrefix: "Code:",
    datePrefix: "Date:",
    haveAccount: "I have an account",
    guestContinue: "Continue as guest",
    changeCode: "Change code",
    scanQrInstead: "Scan QR code",
    scanInvalidQr: "That QR code doesn’t contain a valid join link or access code.",
    scanQrTitle: "Scan invite QR",
    scanQrHint: "Use your camera to scan the QR from your invite or event poster.",
    scanQrStartCamera: "Start camera",
    scanQrStopCamera: "Stop camera",
    scanQrCamUnsupported: "We couldn’t start the camera on this device. Try entering the code manually.",
    scanQrPermissionDenied:
      "Camera permission was denied. Allow camera access in your browser settings, or enter the code manually.",
    scanQrNoCamera: "No usable camera was found. Enter the code manually instead.",
    scanEnterInstead: "Enter code instead",
  },

  globals: {
    errorTitle: "Something went wrong",
    errorBody: "An unexpected error occurred. You can retry, or return to the homepage.",
    tryAgain: "Try again",
    home: "Home",
    notFoundCode: "404",
    notFoundTitle: "Page not found",
    notFoundBody: "The link may be broken or the page may have moved.",
    calistoHome: "Calisto home",
    welcomeLink: "Welcome",
  },

  likes: {
    heartLikeAria: "Like this photo",
    heartUnlikeAria: "Unlike this photo",
    likeCount: "{count} likes",
    likersHeading: "Liked by",
    likersEmpty: "No likes yet",
    toggleFail: "Could not update like. Please try again.",
  },

  guestJoin: {
    loading: "Loading…",
    joining: "Joining event…",
    signedInNavAria: "Account navigation",
    myEvents: "My events",
    manageEvent: "Manage event",
    tagline: "Share your memories from this event.",
    uploadClosedBanner:
      "Uploads are closed for this event (upload window ended). You can still browse the gallery.",
    sectionUpload: "Upload",
    sectionGallery: "Gallery",
    joinInvalidOrNotFound: "That access code isn’t valid for joining right now.",
    joinAlreadyMember: "You’re already part of this event.",
    joinGeneric: "Something went wrong while joining. Try refreshing the page.",
  },

  welcomeModal: {
    eyebrow: "You're invited",
    body: "Join to upload photos & videos and browse the gallery.",
    createAccount: "Create account",
    logIn: "Log in",
    continueGuest: "Continue as guest",
    nicknameLabel: "Your nickname",
    nicknamePlaceholder: "e.g. Ana",
    nicknameError: "Nickname must be 2–30 characters.",
    supabaseMissing: "Supabase is not configured. Please try again later.",
    enterGuest: "Enter as guest",
    genericError: "Something went wrong. Please try again.",
  },

  upload: {
    closedEvent: "Uploads are closed for this event.",
    quotaReached: "This event has reached its photo or video limit.",
    needSignIn: "Please sign in to upload.",
    wrongType: "Only image and video files are supported.",
    failedGeneric: "Upload failed.",
    dropPrompt: "Drag & drop photos or videos here",
    tapBrowse: "or tap to browse",
    uploading: "Uploading…",
  },

  leaveRpc: {
    primaryOrganizer: "The primary organizer can’t leave this way — delete the event in Settings instead.",
    notMember: "You’re not a member of this event anymore.",
    notAuth: "Sign in again to continue.",
    fallback: "Could not leave this event.",
  },

  leave: {
    title: "Leave this event?",
    organizerMessage:
      "You will lose access to uploads and sharing for this event. Photos and videos you already uploaded stay in the gallery for everyone else.",
    guestMessage:
      "You will lose access to this album and uploads. Anything you’ve already uploaded stays in the gallery for other guests.",
    confirm: "Leave event",
    genericError: "Could not leave this event.",
    ctaOrganizerTab: "Leave event",
    guestCtaSame: "Leave event",
    cancelStay: "Stay",
  },

  auth: {
    oauthFail: "Google sign-in didn’t finish. Try again or use email and password.",
    googleStartFail: "Could not start Google sign-in. Try again shortly.",
    checkEmailVerify: "Check your email to confirm your account",
    welcomeEyebrow: "Welcome to",
    brandRest: ".",
    continueGoogle: "Continue with Google",
    dividerOr: "Or",
    dividerBody: "continue with email",
    email: "Email",
    password: "Password",
    signInSubmit: "Sign In",
    forgotPw: "Forgot password?",
    fullName: "Full name",
    createAccountSubmit: "Create Account",
    emailPlaceholderRegister: "you@example.com",
    emailPlaceholderAlt: "you@example.com",
    passwordDots: "••••••••",
    namePlaceholder: "Antonio Kovač",
    legalPrefix: "By continuing you agree to Calisto's",
    terms: "Terms",
    privacy: "Privacy Policy",
    and: "and",
  },

  passwordReset: {
    forgotTitle: "Forgot password",
    forgotSubtitle: "Enter your email and we'll send you a reset link.",
    emailRequired: "Please enter your email address.",
    sendFail: "Could not send reset email. Please try again.",
    sentMessage: "Check your inbox — we sent you a password reset link.",
    sendSubmit: "Send reset link",
    backToSignIn: "Back to sign in",
    verifying: "Verifying your link…",
    expiredTitle: "Link expired",
    expiredBody: "This password reset link has expired or already been used.",
    requestNewLink: "Request a new link",
    accountEyebrow: "Your account",
    setTitle: "Set new password",
    setSubtitle: "Choose a strong password for your account.",
    newPasswordLabel: "New password",
    newPasswordPlaceholder: "••••••••",
    confirmPasswordLabel: "Confirm password",
    confirmPasswordPlaceholder: "••••••••",
    passwordTooShort: "Password must be at least 8 characters.",
    passwordsMismatch: "Passwords don't match.",
    updateFail: "Could not update your password. Please try again.",
    updateSubmit: "Update password",
    successTitle: "Password updated",
    successSubtitle: "Your password has been changed successfully.",
    goToSignIn: "Go to sign in",
  },

  authRail: {
    aria: "Choose sign in or register",
    loginKicker: "Welcome back",
    loginLabel: "Sign in",
    registerKicker: "New to Calisto",
    registerLabel: "Register",
  },

  forbidden: {
    title: "Event not found",
    deny: "You don't have access to this event.",
    dashboardLink: "← Dashboard",
  },

  eventNav: {
    tabOverview: "Overview",
    tabGuests: "Guests",
    tabGallery: "Gallery",
    tabShare: "Share",
    tabPrints: "Prints",
    tabSettings: "Settings",
    subtitle: "Share with guests to let them join.",
    tabsAria: "Event sections",
    myEvents: "My events",
    memoriesCount: "{count} memories",
    guestsCount: "{count} guests",
    bannerHint: "Change your banner style and emoji in Settings.",
  },

  printsTab: {
    kindEyebrow: "Prints",
    kindTitle: "What kind of event is this?",
    kindHint: "We use this to suggest the right invitation and table templates.",
    kindOptionGeneric: "General event",
    kindOptionWedding: "Wedding",
    confirmKindFail: "Could not save. Try again.",
    title: "Prints",
    subtitle: "Choose a layout, add your details, and open the print-ready view when you are ready.",
    categoryInvitation: "Invitations",
    eventDetails: "Event details",
    eventDetailsModalTitle: "Event details",
    eventDetailsClose: "Close",
    categoryTableQr: "Table & QR",
    templateTableMinimal: "Table card · minimal",
    templateTableBold: "Table card · bold",
    templateWeddingInviteSimple: "Wedding invitation · simple",
    templateWeddingInviteFloral: "Wedding invitation · floral",
    templateWeddingInviteBlueFloral: "Wedding invitation · blue floral",
    templateWeddingInviteGeometric: "Wedding invitation · geometric",
    templateWeddingInviteWatercolorCoast: "Wedding invitation · watercolor coast",
    templateWeddingInviteNavyBotanical: "Wedding invitation · navy botanical",
    templateWeddingInviteGrayscaleGlitter: "Wedding invitation · grayscale & gold",
    templateWeddingInviteTerraPill: "Wedding invitation · terracotta floral",
    templateWeddingInviteGoldArchFloral: "Wedding invitation · gold arch floral",
    templateWeddingInviteCherryBlossom: "Wedding invitation · cherry blossom",
    templateWeddingInviteOliveGoldFrame: "Wedding invitation · olive & gold frame",
    templateWeddingInviteGoldCirclesPhoto: "Wedding invitation · gold circles & photo",
    tableTemplateHint: "Opens a print-friendly page with your event QR and join details.",
    invitationsComingSoon: "Coming soon",
    invitationsComingSoonHint: "Invitation printing is on its way.",
    openPrintLayout: "Open print layout",
    openPrintPreview: "Open print preview",
    inviteFieldPartnerA: "Name (first line)",
    inviteFieldPartnerB: "Name (second line)",
    inviteFieldVenue: "Venue or address",
    inviteFieldVenueLineTwo: "Venue address (optional)",
    inviteFieldExtraLine: "Time or tagline (optional)",
    saveDraft: "Save draft",
    draftSaved: "Draft saved.",
    draftSaveFail: "Could not save draft.",
    inviteCarouselPrev: "Previous design",
    inviteCarouselNext: "Next design",
    inviteCarouselSwipeHint: "Swipe sideways to compare invitation designs",
    inviteCarouselCounter: "{current} of {total}",
    inviteFontScaleLabel: "Invitation text size",
    inviteFontScaleHint: "Preview only — does not change your printout. Use this to see how copy fits on each design.",
    inviteAutoFitToggle: "Auto-fit",
    inviteAutoFitNotice: "Text auto-adjusted to fit the design",
    inviteAutoFitUndo: "Undo",
    inviteFieldConnectorLabel: "Symbol between names",
    inviteFieldConnectorHeart: "♥",
    inviteFieldConnectorAmpersand: "&",
    inviteFieldConnectorInfinity: "∞",
    inviteFieldGatheringLabel: "Pre-ceremony gathering",
    inviteFieldGatheringNone: "None",
    inviteFieldGatheringSame: "Same place",
    inviteFieldGatheringSeparate: "Separate places",
    inviteFieldGatheringAddress: "Address",
    inviteFieldGatheringTime: "Time",
    inviteFieldChurchLabel: "Church",
    inviteFieldChurchAddress: "Church address",
    inviteFieldChurchTime: "Ceremony time",
    inviteFieldDinnerLabel: "Dinner reception",
    inviteFieldDinnerAddress: "Reception address",
    inviteFieldDinnerTime: "Reception time",
    inviteFieldQuoteLabel: "Quote",
    inviteFieldQuoteText: "Quote text",
    inviteFieldQuoteAuthor: "Quote author",
    inviteFieldVisibilityTitle: "Show on invitation",
    inviteFieldVisibilityHint: "Turn lines on or off for every design. Hidden fields stay saved but do not print.",
    inviteFieldVisibilityShow: "Show",
    inviteFieldVisibilityHide: "Hide",
    inviteToggleTogetherFamilies: "Together with their families",
    inviteTogglePartnerNames: "Couple names",
    inviteToggleInvitePreamble: "Opening invitation lines",
    inviteToggleCordiallyInvite: "Cordial invitation line",
    inviteToggleWeddingTitle: "“Wedding” title",
    inviteToggleEventDate: "Ceremony date",
    inviteToggleExtraLine: "Time / spelled year",
    inviteToggleVenue: "Venue name",
    inviteToggleVenueLineTwo: "Venue location",
    inviteToggleReception: "Reception to follow",
    inviteToggleGathering: "Pre-ceremony gathering",
    inviteToggleChurch: "Church ceremony",
    inviteToggleDinner: "Dinner reception",
    inviteToggleQuote: "Quote",
    comingSoonHeading: "Coming soon.",
    comingSoonDesc: "Custom invitations, programs, and keepsakes — designed right here and ready to print or order.",
    comingSoonDesc2: "Pick a template, fill in your event details, and we handle the rest.",
    comingSoonBadge: "We're working on it",
  },

  printsSetup: {
    emptyEyebrow: "First-time setup",
    emptyHeading: "Let's build your invitation.",
    emptySubhead: "We'll walk through every detail — names, ceremony, reception — so your details flow into every design.",
    emptyCta: "Start setup",
    emptyMeta: "Takes about 3 minutes · You can pause anytime",
    stepCouple: "The couple",
    stepWhen: "When",
    stepGathering: "Gathering",
    stepCeremony: "Ceremony",
    stepReception: "Reception",
    stepQuote: "Personal touch",
    stepReview: "Review",
    stepEyebrow: "Step {current} of {total}",
    coupleFirstName: "First name",
    coupleSecondName: "Second name",
    coupleSymbol: "Symbol",
    symbolHeart: "Heart",
    symbolAnd: "And",
    symbolInfinity: "Infinity",
    whenDate: "Date",
    whenTime: "Time (optional)",
    gatheringNone: "None",
    gatheringTogether: "Same place",
    gatheringSeparate: "Separate places",
    gatheringAddress: "Address",
    gatheringTime: "Time",
    ceremonyAddress: "Church address",
    ceremonyTime: "Ceremony time",
    receptionVenue: "Reception venue",
    receptionTime: "Reception time",
    quoteLabel: "Quote (optional)",
    quoteAuthor: "Quote author",
    reviewTitle: "Your invitation is ready.",
    reviewSubhead: "Review it on the right, then unlock the print designs.",
    reviewCouple: "Couple",
    reviewDate: "Date",
    reviewGathering: "Gathering",
    reviewCeremony: "Ceremony",
    reviewReception: "Reception",
    backToPrints: "Back to Prints",
    back: "Back",
    continue: "Continue",
    finishSetup: "Finish setup",
    livePreviewEyebrow: "Live Preview",
    livePreviewSub: "Updates as you type",
    editDetails: "Edit details",
    setupComplete: "Setup complete",
    setupCompleteHint: "All invitation details saved. Edit anytime.",
    saveFail: "Could not save. Please try again.",
  },

  overview: {
    yourRole: "Your role",
    uploadCloseLabel: "Time until uploads close",
    uploadCloseShareHint: "See Share for whether guests can upload today.",
    autoDeletionLabel: "Time until automatic event deletion",
    autoDeletionOverdue: "Removal time passed — the next purge job will delete this event.",
    autoDeletionFooterHint:
      "Based on your plan tier from the event date. Changing date or plan updates this. You can still delete manually in Settings.",
    countdownJoin: ", ",
    countdownDayOne: "{n} day",
    countdownDayMany: "{n} days",
    countdownHourOne: "{n} hour",
    countdownHourMany: "{n} hours",
    countdownMinuteOne: "{n} minute",
    countdownMinuteMany: "{n} minutes",
    countdownSubMinute: "Less than a minute",
    countdownMonthOne: "{n} month",
    countdownMonthMany: "{n} months",
    eventStartsIn: "Event starts in",
    uploadWindowEnded: "Upload window ended — uploads are closed.",
    statsTitle: "Statistics",
    statsPhotos: "Photos",
    statsVideos: "Videos",
    statsGuests: "Guests",
    accessCodeTitle: "Access Code",
    copyCode: "Copy code",
    showQr: "Show QR Invite",
    hideQr: "Hide QR",
    scanHint: "Scan to join · same link as the Share tab",
    openShareLink: "Open Share for link & message →",
    recentPhotos: "Recent photos",
    noPhotosHint: "No uploads yet. Open the gallery to see guest photos and videos when they arrive.",
    openGalleryBtn: "Go to Gallery",
    viewGalleryFull: "View full gallery →",
    planLabel: "Plan",
    carouselLatest: "Latest",
    carouselMore: "+more",
    carouselLatestSix: "The latest six",
  },

  share: {
    heading: "Share",
    subtitle: "Send a guest link or access code. Pick a message style, then share or copy.",
    messageStyleEyebrow: "Message style",
    shareInvite: "Share invite",
    shareFootnote:
      "Uses your device share sheet when available; otherwise copies the full message.",
    shareInviteDialogTitle: "You're invited",
    copyFailManual: "Could not copy — try selecting the text manually.",
    shareUnavailable: "Sharing isn't available in this browser. Copy the message below instead.",
    scanQr: "Scan to join",
    joinsSameHint: "Opens the same join page as the link above.",
    printPoster: "Print QR poster",
    previewMessage: "Preview message",
    copyFullMessage: "Copy full message",
    copyJoinLinkBtn: "Copy link",
  },

  gallery: {
    loadFailed: "Failed to load gallery.",
    loading: "Loading gallery…",
    deleteMediaFail: "Could not delete media.",
    deleteTitle: "Delete this upload?",
    deleteBody: "This removes the item from your gallery and deletes the stored file. This cannot be undone.",
    title: "Gallery",
    subtitle: "Browse uploaded photos & videos",
    spotlightLabel: "Today's spotlight",
    addMemory: "Add a memory",
    addMemoryHint: "Tap to upload — or drop a file here",
    memoriesCount: "{count} memories",
    guestsCount: "{count} guests",
    filterAria: "Filter by media type",
    filterAll: "All",
    filterPhotos: "Photos",
    filterVideos: "Videos",
    empty: "No uploads yet.",
    loadMore: "Load more…",
    lightboxAria: "Photo lightbox",
    closeLightboxAria: "Close lightbox",
    prevPhotoAria: "Previous photo",
    nextPhotoAria: "Next photo",
    downloadPhotoAria: "Download this photo",
    downloadBtn: "Download",
    downloadWorking: "Downloading…",
    downloadPhotoFail: "Could not download this photo.",
    downloadFailedWithStatus: "Download failed ({status}).",
    deleteBusy: "…",
    emptyGuest: "No media yet — be the first to upload!",
    openPhotoAria: "Open photo full screen",
    uploadedByYouAria: "Your upload",
    zipExportCardEyebrow: "Primary organizer",
    zipExportTitle: "Bulk ZIP export",
    zipExportBlurb:
      "Download gallery media in one ZIP. We prepare it in the background and email you when it is ready. Download links expire after 24 hours.",
    zipExportPrepare: "Prepare ZIP",
    zipExportModalTitle: "Prepare gallery ZIP",
    zipExportModalBody:
      "Photos are included by default. Turn on the option below to include videos (larger file, longer build).",
    zipExportIncludeVideos: "Include videos",
    zipExportStart: "Start export",
    zipExportQueued: "Queued — we will notify you when it is ready.",
    zipExportRunning: "Building your ZIP…",
    zipExportReady: "Ready to download",
    zipExportFailed: "Export failed",
    zipExportExpired: "Download expired",
    zipExportDownload: "Download ZIP",
    zipExportErrorGeneric: "Could not start export.",
    zipExportErrorPending: "Another export is already in progress.",
    zipExportErrorQueue:
      "The export queue could not be read. If you use your own Supabase project, apply the latest migrations (including `media_zip_exports`). Otherwise try again in a moment.",
    zipExportErrorTooMany: "Too many items for one ZIP. Remove some uploads or export without videos.",
    columnsLabel: "Columns",
    moderationPanelTitle: "Pending approval",
    moderationPanelEmpty: "No pending uploads.",
    moderationApprove: "Approve",
    moderationDiscard: "Discard",
    moderationApproveAll: "Approve all",
    moderationApproveBusy: "…",
    moderationNewBadge: "{count} new",
    moderationPendingBadge: "Pending",
    moderationActionFail: "Could not complete action.",
    newUploadsSectionTitle: "New uploads",
    newUploadsViewAll: "View all",
    newUploadsClose: "Close",
    newUploadsKeep: "Keep",
    newUploadsDelete: "Delete",
  },

  guests: {
    title: "Guests",
    loadFailed: "Failed to load guests.",
    configureSupabase:
      "Set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY in `.env.local` to use event admin features.",
    cannotRemoveOrganizer: "You can't remove the primary organizer.",
    rolesOnlyPrimary: "Only the primary organizer can change roles.",
    notAllowed: "Not allowed.",
    memberNotFound: "Member not found.",
    actionFailed: "Action failed.",
    removeMemberFail: "Could not remove member.",
    updateRoleFail: "Could not update role.",
    removeDialogTitle: "Remove this member?",
    removeDialogBody:
      "They will lose access to this event and its gallery. Uploaded media stays unless you delete it from the gallery.",
    loadingGuests: "Loading guests…",
    empty: "No guests have joined yet.",
    youBadge: "(you)",
    uploadsLine: "Uploads: {photos} photos • {videos} videos",
    promoteCo: "Promote to co‑organizer",
    demoteGuest: "Demote to guest",
    guestLabelFallback: "Guest",
    organizerLabelFallback: "Organizer",
    membersOne: "1 member",
    membersMany: "{n} members",
  },

  supabase: {
    missingTitle: "Supabase not configured",
    settingsBody:
      "Set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY in `.env.local` to edit event settings.",
    galleryBody:
      "Set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY in `.env.local` to load the gallery.",
  },

  settingsPage: {
    title: "Settings",
    eventsLink: "Events",
  },

  settingsClient: {
    profileEyebrow: "Profile",
    signedInAs: "Signed in as ",
    anon: "—",
    appearanceEyebrow: "Appearance",
    languageEyebrow: "Language",
    langEnglish: "English",
    langHrvatski: "Hrvatski",
    langDeutsch: "Deutsch",
    themeDarkLabel: "Dark",
    themeLightLabel: "Light",
    appliesNote: "Applies to pages that support light and dark.",
    signOut: "Sign out",
    backEvents: "← Back to events",
    uploadNameEyebrow: "Uploads & gallery",
    uploadNameLabel: "Name on your uploads",
    uploadNameHint:
      "Shown next to photos and videos you add in event galleries. Uses your profile; refresh the gallery after saving.",
    uploadNamePlaceholder: "e.g. Alex",
    saveUploadName: "Save name",
    uploadNameSaved: "Saved.",
    uploadNameSaveFail: "Could not save. Try again.",
    uploadNameNotSignedIn: "Not signed in.",
  },

  settingsTab: {
    heading: "Settings",
    subtitle: "Only you (the primary organizer) see this tab — update how this event appears in Calisto.",
    sectionNameIcon: "Name & icon",
    eventNameLabel: "Event name",
    namePlaceholder: "e.g. Kyle & Laura",
    iconEyebrow: "Event icon",
    chooseEmoji: "Choose emoji",
    closePicker: "Close picker",
    noIcon: "No icon",
    emojiAria: "Selected emoji",
    emojiPickerAria: "Emoji picker",
    iconHint:
      "Shown next to your event title in the header. If you skip an icon, a default is used in the nav only.",
    saveChanges: "Save changes",
    reset: "Reset",
    sectionSchedule: "Event details",
    scheduleNoteLead: "Saved as ",
    scheduleNoteTrail:
      "(calendar). Changing the date or plan updates guest upload windows and media limits for this event — in-app checkout for paid tiers is not live yet.",
    eventDateUtc: "Event date (UTC calendar day)",
    planTier: "Plan tier",
    saveSchedule: "Save date & plan",
    joinCodeEyebrow: "Guest join code",
    dashboardBack: "Back to dashboard",
    dangerEyebrow: "Danger zone",
    deletePhraseWord: "DELETE",
    confirmMismatch: "Confirmation didn’t match. Enter the saved event title exactly, or type DELETE.",
    deleteStorageIncomplete: "The event was removed but some files couldn’t be deleted from storage. Contact support.",
    deleteFail: "Could not delete this event.",
    genericSaveFail: "Could not save changes.",
    validDateNeeded: "Choose a valid event date.",
    scheduleSaveFail: "Could not update date or plan.",
    dateLockNotice: "The event has already started — the date is locked to prevent extending upload or deletion windows.",
    deleteTitleForever: "Delete event forever?",
    deleteDialogBody:
      "Everyone loses access immediately. Guests, gallery files, uploads, invite codes — all removed.",
    deleteConfirmLabel: "Yes, delete permanently",
    deleteDangerNote: "Permanent deletion cannot be undone.",
    deleteInstructionLead: "Confirm by typing either the saved event title ",
    deleteInstructionTrail: "exactly as stored, or the word ",
    deleteConfirmPhraseLabel: "Confirmation",
    deletePlaceholderTitleOrWord: "Title or DELETE",
    deleteButton: "Delete this event completely",
    exactParen: "(exact)",
    moderationHeading: "Photo moderation",
    moderationHint: "When on, guest uploads are hidden until you approve them. You can change this at any time.",
    moderationOn: "Moderation on",
    moderationOff: "Moderation off",
    moderationSaveFail: "Could not update moderation setting.",
  },

  validateCreate: {
    nameRequired: "Event name is required. Please go back and enter a name.",
  },

  createStep1: {
    eyebrow: "New event",
    title: "Create event",
    description: "You'll automatically become the organizer.",
    eventTitleLabel: "Event title",
    namePlaceholder: "e.g. Kyle & Laura",
    eventIconEyebrow: "Event icon",
    eventDateLabel: "Event date",
    continuePlan: "Continue to plan →",
    searchEmojiHint: "Search or browse all emojis. Your choice appears in the event header.",
    noEmojiBtn: "No emoji",
    defaultEmojiAria: "Selected emoji",
    moderationToggleLabel: "Review photos before guests can see them",
    moderationToggleHint: "You can change this later in Settings.",
  },

  createStep2: {
    eyebrow: "Step 2 of 3",
    heading: "Choose a plan",
    description: "Select the plan that fits your event size.",
    priceEyebrow: "Price",
    sale: "Sale",
    popularBadge: "Popular",
    unlimited: "Unlimited",
    guestsPhotosVideos: "{guests} guests • {photos} photos • {videos} videos",
    uploadsOpenAfterDays: "Uploads open for {n} days after the event",
    moreDetailsAria: "More details about the {plan} plan",
    detailRegionAria: "{plan} plan details",
    rowGuests: "Guests",
    rowPhotos: "Photos",
    rowVideos: "Videos",
    rowUploadWindow: "Upload window",
    uploadWindowDays: "{n} days",
    tipChangePlanLater: "Tip: You can change plans later from your event settings.",
    continuePayment: "Continue to payment →",
    payWord: "payment",
    planWord: "plan",
    dayWord: "day",
    daysWord: "days",
  },

  createStep3: {
    validationBack: "Go back to details",
    checkingSession: "Checking your session…",
    needAuthHeading: "Sign in to create your event",
    needAuthBody:
      "You need an account to finish creating this event. We'll keep your draft so you can continue on return.",
    logInBtn: "Log in",
    createAcctBtn: "Create account",
    checkoutFailGeneric: "Could not start checkout.",
    createFail: "Could not create event.",
    stepEyebrow: "Step 3 · Review & create",
    confirmHeading: "Confirm your event",
    confirmBodyLeadBeforeName: "You’re about to create ",
    confirmBodyBetweenNameDate: " on ",
    confirmBodyTierWord: " on the ",
    confirmBodyPlanSuffix: " tier",
    confirmBodyPaidTail:
      " You'll confirm payment securely with Stripe, then your event opens with the tier's limits.",
    confirmBodyFreeTier:
      "The free tier is confirmed here with no checkout — invite guests right away.",
    selectedPlanEyebrow: "Selected plan",
    saleBadge: "Sale",
    priceNotePaid: "Price includes VAT where applicable — charged once when you confirm in Stripe.",
    priceNoteFree: "Free tier stays free.",
    footnotePaid: "You’ll jump to Stripe to pay; when it succeeds your event opens right away.",
    footnoteFree: "No charge — your album and invite code go live immediately.",
    btnOpeningCheckout: "Opening checkout…",
    btnCreating: "Creating…",
    btnStripe: "Continue to Stripe",
    btnConfirmFree: "Confirm and create event",
  },

  stripeComplete: {
    missingSession: "Missing checkout session.",
    fulfillFailGeneric: "Could not finish checkout.",
    fulfillRetryHint: 'If payment just finished, wait a moment and use "Try again".',
    noEventId: "Checkout finished but event id was not returned.",
    tryAgain: "Try again",
    goDashboard: "Go to dashboard",
    finalizing: "Finalizing payment and creating your event…",
  },

  onboardingForm: {
    welcomeEyebrow: "Welcome",
    title: "Tell us about your event",
    subtitle: "This personalizes your space. You can create your first event from the dashboard next.",
    kindEyebrow: "What are you planning?",
    displayNameLabel: "What should we call you? (optional)",
    namePlaceholderShort: "e.g. Alex",
    choosePlanning: "Choose what you're planning.",
    saveFail: "Could not save. Try again.",
    notSignedIn: "Not signed in.",
    continueDashboard: "Continue to dashboard",
  },

  onboardingKinds: {
    wedding: "Wedding",
    birthday: "Birthday",
    corporate: "Corporate",
    other: "Something else",
  },

  planTiersPage: {
    eyebrow: "Plans",
    title: "Plan tiers",
    subtitle: "A quick summary of guest and upload limits.",
    back: "Back",
    uploadBadge: "{n} days uploads",
    colGuests: "Guests",
    colPhotos: "Photos",
    colVideos: "Videos",
  },

  print: {
    deniedTitle: "Event not found",
    deniedDeny: "You don't have access to this event.",
    backDashboard: "← Dashboard",
    backShare: "← Back to Share",
    print: "Print",
    heroEyebrow: "Scan to upload photos & videos",
    footerGoToLead: "Or go to ",
    footerGoToTrail: " and enter code:",
    sheetHelper:
      "Two identical table cards per sheet. Cut along the dashed line to place one card on each table.",
    cutHere: "Cut here",
    downloadPdf: "Download PDF",
    downloadQr: "Download QR",
    changeTheme: "Change theme",
    previewPdf: "Preview",
    paperSectionLabel: "Paper size",
    printThemeLabel: "Theme",
    printSheetChip: "2 cards per {paper} · cut in the middle",
    paperA4: "A4",
    paperLetter: "US Letter",
    templateSectionLabel: "Layout",
    templateTableMinimal: "Minimal",
    templateTableBold: "Bold",
    templateQrClean: "Clean",
    templateQrGold: "Gold",
    templateQrDark: "Dark",
    templateQrSimple: "Simple",
    templateQrRomantic: "Romantic",
    templateQrLuxurious: "Luxurious",
    templateQrBotanical: "Botanical",
    templateQrArtDeco: "Art Deco",
    templateQrPlayful: "Playful",
    templateQrCelestial: "Celestial",
    templateQrCoastal: "Coastal",
    templateQrBoho: "Boho",
    templateQrNoir: "Noir",
    templateQrWatercolor: "Watercolor",
    templateQrRetro: "Retro",
    templateQrTropical: "Tropical",
    templateQrScandi: "Scandi",
    templateQrSunset: "Sunset",
    templateQrRustic: "Rustic",
    qrCardSimpleTagline: "SCAN TO JOIN",
    qrCardSimpleHeadline: "Share the moment.",
    qrCardSimpleBody: "Point your camera at the code to drop your photos straight into our shared album.",
    qrCardRomanticTagline: "Together with joy",
    qrCardRomanticBody: "Scan to share the photos you capture and relive every tender moment with us.",
    qrCardRomanticCta: "scan me",
    qrCardLuxuriousBody: "An evening to remember. Scan to contribute your photographs to our private gallery.",
    qrCardBotanicalTagline: "Gather & bloom",
    qrCardBotanicalBody: "Help our garden of memories grow — scan to add the moments you capture today.",
    qrCardArtDecoBody: "A night of glamour awaits. Scan to capture & share the magic.",
    qrCardPlayfulBadge: "Let's celebrate",
    qrCardPlayfulHeadline: "Snap it. Share it!",
    qrCardPlayfulBody: "Scan the code and toss every photo into our shared party album.",
    qrCardCelestialTagline: "Under the stars",
    qrCardCelestialBody: "Capture the magic of tonight — scan to share your photos with us.",
    qrCardCoastalTagline: "By the sea",
    qrCardCoastalBody: "Let the tide of memories roll in — scan to add your photos to our album.",
    qrCardBohoTagline: "Wild & free",
    qrCardBohoBody: "Gather close and share the moments you capture today.",
    qrCardNoirSub: "SCAN · SHARE · RELIVE",
    qrCardNoirHeadline: "SHARE THE NIGHT",
    qrCardNoirBody: "Point your camera at the code to drop photos into our shared album.",
    qrCardWatercolorTagline: "A day to remember",
    qrCardWatercolorBody: "Paint our album with your colours — scan to share the moments you capture.",
    qrCardRetroBadge: "Good vibes only",
    qrCardRetroBody: "Scan the code & drop your best shots into our shared album.",
    qrCardTropicalTagline: "Aloha & celebrate",
    qrCardTropicalBody: "Soak up the sun and share your snapshots — scan to join our album.",
    qrCardScandiTagline: "Hej & welcome",
    qrCardScandiBody: "Scan the code to drop your photos straight into our shared album.",
    qrCardSunsetTagline: "Golden hour",
    qrCardSunsetBody: "Chase the light with us — scan to share every photo from tonight.",
    qrCardRusticTagline: "Save our memories",
    qrCardRusticBody: "Scan to add the photos you capture to our shared album.",
    templateWeddingInviteSimple: "Wedding · simple",
    templateWeddingInviteFloral: "Wedding · floral",
    templateWeddingInviteBlueFloral: "Wedding · blue floral",
    templateWeddingInviteGeometric: "Wedding · geometric",
    templateWeddingInviteWatercolorCoast: "Wedding · watercolor coast",
    templateWeddingInviteNavyBotanical: "Wedding · navy botanical",
    templateWeddingInviteGrayscaleGlitter: "Wedding · black & gold",
    templateWeddingInviteTerraPill: "Wedding · terracotta floral",
    templateWeddingInviteGoldArchFloral: "Wedding · gold arch floral",
    templateWeddingInviteCherryBlossom: "Wedding · cherry blossom",
    templateWeddingInviteOliveGoldFrame: "Wedding · olive & gold frame",
    templateWeddingInviteGoldCirclesPhoto: "Wedding · gold circles & photo",
    inviteTogetherWithOurFamilies: "TOGETHER WITH OUR FAMILIES",
    inviteHonorUniteMarriage: "we request the honor of your presence as we unite our lives in marriage",
    inviteGlitterCordiallyLine: "you are cordially invited to",
    inviteGlitterWeddingOfLine: "the wedding of",
    inviteGlitterTogetherFamilies: "Together with their families",
    inviteGlitterCordiallyInviteCaps: "cordially invite you to their",
    inviteGlitterWeddingWord: "Wedding",
    inviteGlitterOn: "on",
    inviteTerraPleaseJoinUsFor: "please join us for",
    inviteWatercolorPleaseJoinUs: "Please join us",
    inviteWatercolorForCeremony: "for our wedding ceremony",
    inviteTerraTheWeddingOf: "the wedding of",
    inviteGoldArchHeadline: "You're invited to attend the wedding of",
    inviteCherryPreambleStart: "you are cordially",
    inviteCherryPreambleScript: "invited",
    inviteCherryPreambleMid: "to attend the",
    inviteCherryPreambleEnd: "wedding of",
    inviteOliveWithLove: "with love",
    inviteOliveCordiallyLine1: "we cordially invite you",
    inviteOliveCordiallyLine2: "to the wedding ceremony of",
    inviteCategoryLabel: "Invitations",
    tableCategoryLabel: "Table cards",
    inviteTogetherWithFamilies: "TOGETHER WITH THEIR FAMILIES",
    inviteCelebrationOn: "INVITE YOU TO JOIN THEIR WEDDING CELEBRATION ON",
    inviteReceptionFollow: "Reception to follow",
    inviteGoldCirclesYoureInvited: "You're invited to the wedding of",
    inviteGoldCirclesUploadPhoto: "Upload photo",
    inviteGoldCirclesChangePhoto: "Change photo",
    inviteGoldCirclesUploading: "Uploading…",
    inviteGoldCirclesUploadError: "Upload failed. Try again.",
    inviteWithJoyYouAre: "with joy you are",
    inviteInvitedToWeddingOf: "invited to the wedding of",
    inviteAnd: "and",
    inviteDetailsGathering: "Gathering",
    inviteDetailsChurch: "Ceremony",
    inviteDetailsDinner: "Reception",
    sheetHelperInvitation: "Portrait invitation preview. Paper size still applies when you print.",
    backPrints: "← Back to Prints",
    invitationUnavailableTitle: "This layout is not available",
    invitationUnavailable: "This invitation layout is not available for this event type.",
    posterLanguageLabel: "Poster language",
  },

  languagePicker: {
    label: "Language",
    locales: {
      en: "English",
      hr: "Croatian",
      de: "German",
    },
  },
};

export type AppUiDict = typeof APP_UI_EN;
