import type { AppUiDict } from "./en";

export const APP_UI_HR: AppUiDict = {
  defaults: {
    eventTitle: "Događaj",
    organizer: "Organizator",
    guest: "Gost",
  },

  theme: {
    light: "svijetla",
    dark: "tamna",
  },

  common: {
    cancel: "Odustani",
    delete: "Obriši",
    remove: "Ukloni",
    refresh: "Osvježi",
    copied: "Kopirano!",
    loading: "Učitavanje…",
    working: "Radi se…",
    back: "← Natrag",
    stay: "Ostani",
    pending: "Na čekanju",
    errorFallback: "Greška",
    configuringSupabase: "Konfiguriraj Supabase za pregled uploada.",
    loadCountsHint: "Konfiguriraj Supabase za učitavanje stalnih statistika.",
  },

  quotas: {
    unlimitedPlan: "Neograničen plan",
    ofCount: "od {n}",
    notOnPlan: "Razina nije u ovom paketu",
  },

  plans: {
    free: "Besplatno",
    standard: "Standard",
    plus: "Plus",
    premium: "Premium",
    max: "Max",
  },

  invites: {
    code: "Pristupni kod",
    link: "Poveznica za pridruživanje",
    introShort: "Pridružite nam se na događaju:",
    introFriendly: "Pozvani ste na",
    introFormal: "Uz sve poštovanje pozvani ste na",
    ctaShort: "Vidimo se!",
    ctaFriendly: "Jedva čekamo slaviti s vama!",
    ctaFormal: "Za nas bi bila čast vaša prisutnost.",
    templateShort: "Kratko",
    templateFriendly: "Prijateljski",
    templateFormal: "Formalno",
  },

  shell: {
    brand: "Calisto",
    navHome: "Početna",
    navSettings: "Postavke",
    joinCta: "Pridruži se",
    newEventAria: "Novi događaj",
    newEventShort: "+",
    newEventLabel: "+ Novi događaj",
    eventBreadcrumb: "← Početna",
    eventContext: "Događaj",
  },

  accountMenu: {
    triggerSr: "Izbornik računa",
    panelAria: "Račun",
    signedInLabel: "Prijavljeni ste",
    profile: "Profil",
    settings: "Postavke",
    help: "Pomoć",
    themeLabel: "Tema",
    signingOut: "Odjava…",
    signOut: "Odjavi se",
  },

  dashboard: {
    eyebrow: "Nadzorna ploča",
    helloTemplate: "Zdravo, {name}",
    fallbackName: "gost",
    subtitle: "Događaji koje organizirate, na kojima ste suorganizator ili ste im se pridružili kao gost.",
    joinWithCode: "Pridruži se kodom",
    createEvent: "+ Stvori događaj",
    yourEvents: "Vaši događaji",
    memberOne: "član",
    membersMany: "članova",
    roleOrganizer: "Organizator",
    roleCoOrganizer: "Suorganizator",
    roleGuest: "Gost",
    emptyHint: "Stvorite novi događaj ili se pridružite postojećem kodom od organizatora.",
    moreHint: "Stvorite još jedan događaj ili se pridružite kodom od organizatora.",
  },

  joinEntryFooter: {
    howItWorks: "Kako Calisto radi",
    home: "Početna",
  },

  joinForm: {
    title: "Pridružite se događaju",
    subtitle: "Unesite pristupni kod koji je podijelio organizator.",
    accessCodeLabel: "Pristupni kod",
    hintFormats: "Savjet: kodovi izgledaju kao ",
    joinCta: "Pridruži se događaju",
    codeTooShort: "Unesite kod s pozivnice (najmanje 4 znaka).",
    notFound: "Nismo pronašli događaj za taj kod. Provjerite i pokušajte ponovo.",
    genericError: "Nešto je pošlo po zlu pri provjeri koda. Pokušajte ponovo.",
    previewEyebrow: "Pregled događaja",
    codePrefix: "Kod:",
    datePrefix: "Datum:",
    haveAccount: "Imam račun",
    guestContinue: "Nastavi kao gost",
    changeCode: "Promijeni kod",
    scanQrInstead: "Skeniraj QR kod",
    scanInvalidQr: "Taj QR kod ne sadrži valjanu poveznicu za pridruživanje niti pristupni kod.",
    scanQrTitle: "Skeniraj QR s pozivnice",
    scanQrHint: "Kamerom skeniraj QR kod s pozivnice ili postera događaja.",
    scanQrStartCamera: "Pokreni kameru",
    scanQrStopCamera: "Zaustavi kameru",
    scanQrCamUnsupported: "Kameru nismo mogli pokrenuti na ovom uređaju. Unesi kod ručno.",
    scanQrPermissionDenied:
      "Pristup kameri je odbijen. Dozvoli pristup u postavkama preglednika ili unesi kod ručno.",
    scanQrNoCamera: "Nije pronađena upotrebljiva kamera. Umjesto toga unesi kod ručno.",
    scanEnterInstead: "Unesi kod",
  },

  globals: {
    errorTitle: "Nešto je pošlo po zlu",
    errorBody:
      "Dogodila se neočekivana greška. Možete pokušati ponovo ili se vratiti na početnu stranicu.",
    tryAgain: "Pokušaj ponovo",
    home: "Početna",
    notFoundCode: "404",
    notFoundTitle: "Stranica nije pronađena",
    notFoundBody: "Poveznica može biti kriva ili je stranica premještena.",
    calistoHome: "Calisto početna",
    welcomeLink: "Dobro došli",
  },

  likes: {
    heartLikeAria: "Lajkaj fotografiju",
    heartUnlikeAria: "Ukloni lajk",
    likeCount: "{count} lajkova",
    likersHeading: "Lajkali",
    likersEmpty: "Još nema lajkova",
    toggleFail: "Lajk nije mogao biti ažuriran. Pokušajte ponovo.",
  },

  guestJoin: {
    loading: "Učitavanje…",
    joining: "Pridruživanje događaju…",
    signedInNavAria: "Navigacija računa",
    myEvents: "Moji događaji",
    manageEvent: "Upravljaj događajem",
    tagline: "Podijelite uspomene s ovog događaja.",
    uploadClosedBanner:
      "Upload je zatvoren za ovaj događaj (period uploada je završio). I dalje možete pregledavati galeriju.",
    sectionUpload: "Upload",
    sectionGallery: "Galerija",
    joinInvalidOrNotFound: "Taj kod trenutačno ne vrijedi za pridruživanje.",
    joinAlreadyMember: "Već ste dio ovog događaja.",
    joinGeneric: "Nešto je pošlo po zlu pri pridruživanju. Pokušajte osvježiti stranicu.",
  },

  welcomeModal: {
    eyebrow: "Pozvani ste",
    body: "Pridružite se za upload fotografija i videozapisa te pregled galerije.",
    createAccount: "Stvori račun",
    logIn: "Prijava",
    continueGuest: "Nastavi kao gost",
    nicknameLabel: "Vaš nadimak",
    nicknamePlaceholder: "npr. Ana",
    nicknameError: "Nadimak mora imati između 2 i 30 znakova.",
    supabaseMissing: "Supabase nije konfiguriran. Pokušajte ponovo kasnije.",
    enterGuest: "Uđi kao gost",
    genericError: "Nešto je pošlo po zlu. Pokušajte ponovo.",
  },

  upload: {
    closedEvent: "Upload je zatvoren za ovaj događaj.",
    quotaReached: "Ovaj je događaj dosegao granicu za fotografije ili videozapise.",
    needSignIn: "Prijavite se za upload.",
    wrongType: "Podržane su samo slike i videozapisi.",
    failedGeneric: "Upload nije uspio.",
    dropPrompt: "Povuci i ispusti fotografije ili videozapise ovdje",
    tapBrowse: "ili dodirnite za pregled datoteka",
    uploading: "Upload…",
  },

  leaveRpc: {
    primaryOrganizer:
      "Primarni organizator tako ne može napustiti događaj — umjesto toga ga obrišite u Postavkama.",
    notMember: "Više niste član ovog događaja.",
    notAuth: "Ponovno se prijavite za nastavak.",
    fallback: "Nismo mogli napustiti ovaj događaj.",
  },

  leave: {
    title: "Napustiti događaj?",
    organizerMessage:
      "Izgubit ćete pristup uploadu i dijeljenju za ovaj događaj. Fotografije i videi koje ste već uploadali ostaju u galeriji za ostale.",
    guestMessage:
      "Izgubit ćete pristup ovom albumu i uploadu. Sve što ste već poslali ostaje u galeriji za druge goste.",
    confirm: "Napusti događaj",
    genericError: "Nismo mogli napustiti ovaj događaj.",
    ctaOrganizerTab: "Napusti događaj",
    guestCtaSame: "Napusti događaj",
    cancelStay: "Ostani",
  },

  auth: {
    oauthFail: "Google prijava se nije dovršila. Pokušajte ponovo ili koristite e‑poštu i lozinku.",
    googleStartFail: "Nismo mogli pokrenuti Google prijavu. Pokušajte uskoro ponovo.",
    checkEmailVerify: "Provjerite e‑poštu za potvrdu računa",
    welcomeEyebrow: "Dobrodošli u",
    brandRest: ".",
    continueGoogle: "Nastavi s Googleom",
    dividerOr: "Ili",
    dividerBody: "nastavi s e‑poštom",
    email: "E‑pošta",
    password: "Lozinka",
    signInSubmit: "Prijava",
    forgotPw: "Zaboravili ste lozinku?",
    fullName: "Puno ime",
    createAccountSubmit: "Registracija",
    emailPlaceholderRegister: "vi@primjer.com",
    emailPlaceholderAlt: "vi@primjer.com",
    passwordDots: "••••••••",
    namePlaceholder: "Antonio Horvat",
    legalPrefix: "Nastavljanjem prihvaćate Calisto",
    terms: "Uvjeti",
    privacy: "Pravila privatnosti",
    and: "i",
  },

  passwordReset: {
    forgotTitle: "Zaboravljena lozinka",
    forgotSubtitle: "Unesite e-mail i poslat ćemo vam link za resetiranje.",
    emailRequired: "Molimo unesite svoju e-mail adresu.",
    sendFail: "Slanje e-maila nije uspjelo. Pokušajte ponovo.",
    sentMessage: "Provjerite pretinac — poslali smo vam link za resetiranje lozinke.",
    sendSubmit: "Pošalji link",
    backToSignIn: "Natrag na prijavu",
    verifying: "Provjera linka…",
    expiredTitle: "Link je istekao",
    expiredBody: "Ovaj link za resetiranje lozinke je istekao ili je već korišten.",
    requestNewLink: "Zatraži novi link",
    accountEyebrow: "Vaš račun",
    setTitle: "Postavi novu lozinku",
    setSubtitle: "Odaberite jaku lozinku za vaš račun.",
    newPasswordLabel: "Nova lozinka",
    newPasswordPlaceholder: "••••••••",
    confirmPasswordLabel: "Potvrdi lozinku",
    confirmPasswordPlaceholder: "••••••••",
    passwordTooShort: "Lozinka mora imati najmanje 8 znakova.",
    passwordsMismatch: "Lozinke se ne podudaraju.",
    updateFail: "Ažuriranje lozinke nije uspjelo. Pokušajte ponovo.",
    updateSubmit: "Ažuriraj lozinku",
    successTitle: "Lozinka ažurirana",
    successSubtitle: "Vaša lozinka je uspješno promijenjena.",
    goToSignIn: "Idi na prijavu",
  },

  authRail: {
    aria: "Odaberite prijavu ili registraciju",
    loginKicker: "Dobrodošli natrag",
    loginLabel: "Prijava",
    registerKicker: "Novi ste na Calistu?",
    registerLabel: "Registracija",
  },

  forbidden: {
    title: "Događaj nije pronađen",
    deny: "Nemate pristup ovom događaju.",
    dashboardLink: "← Nadzorna ploča",
  },

  eventNav: {
    tabOverview: "Pregled",
    tabGuests: "Gosti",
    tabGallery: "Galerija",
    tabShare: "Dijeli",
    tabPrints: "Ispisi",
    tabSettings: "Postavke",
    subtitle: "Podijelite s gostima da se mogu pridružiti.",
    tabsAria: "Odjeljci događaja",
    myEvents: "Moji događaji",
    memoriesCount: "{count} uspomena",
    guestsCount: "{count} gostiju",
  },

  printsTab: {
    kindEyebrow: "Ispisi",
    kindTitle: "Kakav je ovo događaj?",
    kindHint: "Koristimo to za prijedlog odgovarajućih predložaka pozivnica i kartica za stol.",
    kindOptionGeneric: "Opći događaj",
    kindOptionWedding: "Vjenčanje",
    confirmKindFail: "Spremanje nije uspjelo. Pokušajte ponovno.",
    title: "Ispisi",
    subtitle: "Odaberite raspored, unesite podatke i otvorite prikaz spreman za ispis kad ste spremni.",
    categoryInvitation: "Pozivnice",
    eventDetails: "Detalji događaja",
    eventDetailsModalTitle: "Detalji događaja",
    eventDetailsClose: "Zatvori",
    categoryTableQr: "Stol i QR",
    templateTableMinimal: "Kartica za stol · jednostavno",
    templateTableBold: "Kartica za stol · istaknuto",
    templateWeddingInviteSimple: "Pozivnica za vjenčanje · jednostavno",
    templateWeddingInviteFloral: "Pozivnica za vjenčanje · cvijetna",
    templateWeddingInviteBlueFloral: "Pozivnica za vjenčanje · plavo-cvijetna",
    templateWeddingInviteGeometric: "Pozivnica za vjenčanje · geometrijska",
    templateWeddingInviteWatercolorCoast: "Pozivnica za vjenčanje · akvarel obala",
    templateWeddingInviteNavyBotanical: "Pozivnica za vjenčanje · mornarski botanički",
    templateWeddingInviteGrayscaleGlitter: "Pozivnica za vjenčanje · siva i zlatna",
    templateWeddingInviteTerraPill: "Pozivnica za vjenčanje · terakota i cvijeće",
    templateWeddingInviteGoldArchFloral: "Pozivnica za vjenčanje · zlatni luk i cvijeće",
    templateWeddingInviteCherryBlossom: "Pozivnica za vjenčanje · trešnjev cvijet",
    templateWeddingInviteOliveGoldFrame: "Pozivnica za vjenčanje · maslina i zlatni okvir",
    tableTemplateHint: "Otvara stranicu prilagođenu ispisu s QR kodom događaja i detaljima pridruživanja.",
    openPrintLayout: "Otvori raspored za ispis",
    openPrintPreview: "Otvori pregled ispisa",
    inviteFieldPartnerA: "Ime (prvi red)",
    inviteFieldPartnerB: "Ime (drugi red)",
    inviteFieldVenue: "Mjesto ili adresa",
    inviteFieldVenueLineTwo: "Adresa mjesta (neobavezno)",
    inviteFieldExtraLine: "Vrijeme ili slogan (neobavezno)",
    saveDraft: "Spremi skicu",
    draftSaved: "Skica spremljena.",
    draftSaveFail: "Skicu nije bilo moguće spremiti.",
    inviteCarouselPrev: "Prethodni dizajn",
    inviteCarouselNext: "Sljedeći dizajn",
    inviteCarouselSwipeHint: "Povucite u stranu za usporedbu dizajna pozivnica",
    inviteCarouselCounter: "{current} od {total}",
    inviteFontScaleLabel: "Veličina teksta pozivnice",
    inviteFontScaleHint:
      "Samo pregled — ne mijenja ispis. Koristite za provjeru kako tekst stoji na svakom dizajn.",
    inviteAutoFitToggle: "Auto-fit",
    inviteAutoFitNotice: "Tekst automatski prilagođen dizajnu",
    inviteAutoFitUndo: "Poništi",
    inviteFieldConnectorLabel: "Simbol između imena",
    inviteFieldConnectorHeart: "♥",
    inviteFieldConnectorAmpersand: "&",
    inviteFieldConnectorInfinity: "∞",
    inviteFieldGatheringLabel: "Predceremonijalnog skup",
    inviteFieldGatheringNone: "Nema",
    inviteFieldGatheringSame: "Isto mjesto",
    inviteFieldGatheringSeparate: "Odvojena mjesta",
    inviteFieldGatheringAddress: "Adresa",
    inviteFieldGatheringTime: "Vrijeme",
    inviteFieldChurchLabel: "Crkva",
    inviteFieldChurchAddress: "Adresa crkve",
    inviteFieldChurchTime: "Vrijeme ceremonije",
    inviteFieldDinnerLabel: "Domjenak",
    inviteFieldDinnerAddress: "Adresa domjenka",
    inviteFieldDinnerTime: "Vrijeme domjenka",
    inviteFieldQuoteLabel: "Citat",
    inviteFieldQuoteText: "Tekst citata",
    inviteFieldQuoteAuthor: "Autor citata",
    inviteFieldVisibilityTitle: "Prikaži na pozivnici",
    inviteFieldVisibilityHint: "Uključite ili isključite retke za sve dizajne. Skriveni podaci ostaju spremljeni, ali se ne ispisuju.",
    inviteFieldVisibilityShow: "Prikaži",
    inviteFieldVisibilityHide: "Sakrij",
    inviteToggleTogetherFamilies: "Zajedno s obiteljima",
    inviteTogglePartnerNames: "Imena mladenaca",
    inviteToggleInvitePreamble: "Uvodne linije pozivnice",
    inviteToggleCordiallyInvite: "Srdačna pozivna linija",
    inviteToggleWeddingTitle: "Naslov „Vjenčanje“",
    inviteToggleEventDate: "Datum ceremonije",
    inviteToggleExtraLine: "Vrijeme / godina riječima",
    inviteToggleVenue: "Naziv lokacije",
    inviteToggleVenueLineTwo: "Adresa lokacije",
    inviteToggleReception: "Svečana večera nakon",
    inviteToggleGathering: "Okupljanje prije ceremonije",
    inviteToggleChurch: "Crkvena ceremonija",
    inviteToggleDinner: "Večera / prijem",
    inviteToggleQuote: "Citat",
  },

  printsSetup: {
    emptyEyebrow: "Postavljanje pozivnice",
    emptyHeading: "Izgradimo vašu pozivnicu.",
    emptySubhead: "Provest ćemo vas kroz sve detalje — imena, ceremonija, prijem — kako bi vaši podaci odgovarali svakom dizajnu.",
    emptyCta: "Počni postavljanje",
    emptyMeta: "Trajanje oko 3 minute · Možete pauzirati u bilo kada",
    stepCouple: "Par",
    stepWhen: "Kada",
    stepGathering: "Okupljanje",
    stepCeremony: "Ceremonija",
    stepReception: "Prijem",
    stepQuote: "Osobni dodir",
    stepReview: "Pregled",
    stepEyebrow: "Korak {current} od {total}",
    coupleFirstName: "Prvo ime",
    coupleSecondName: "Drugo ime",
    coupleSymbol: "Simbol",
    symbolHeart: "Srce",
    symbolAnd: "I",
    symbolInfinity: "Beskonačnost",
    whenDate: "Datum",
    whenTime: "Vrijeme (opcionalno)",
    gatheringNone: "Bez",
    gatheringTogether: "Isto mjesto",
    gatheringSeparate: "Odvojena mjesta",
    gatheringAddress: "Adresa",
    gatheringTime: "Vrijeme",
    ceremonyAddress: "Adresa crkve",
    ceremonyTime: "Vrijeme ceremonije",
    receptionVenue: "Mjesto prijema",
    receptionTime: "Vrijeme prijema",
    quoteLabel: "Citat (opcionalno)",
    quoteAuthor: "Autor citata",
    reviewTitle: "Vaša pozivnica je spremna.",
    reviewSubhead: "Pregledajte je s desne strane, zatim otključajte dizajne za ispis.",
    reviewCouple: "Par",
    reviewDate: "Datum",
    reviewGathering: "Okupljanje",
    reviewCeremony: "Ceremonija",
    reviewReception: "Prijem",
    backToPrints: "Natrag na ispise",
    back: "Natrag",
    continue: "Dalje",
    finishSetup: "Završi postavljanje",
    livePreviewEyebrow: "Pregled uživo",
    livePreviewSub: "Ažurira se dok tipkate",
    editDetails: "Uredi detalje",
    setupComplete: "Postavljanje završeno",
    setupCompleteHint: "Svi detalji pozivnice su spremljeni. Uredite bilo kada.",
    saveFail: "Nije moguće spremiti. Pokušajte ponovo.",
  },

  overview: {
    yourRole: "Vaša uloga",
    uploadCloseLabel: "Preostalo vrijeme do zatvaranja uploada",
    uploadCloseShareHint: "U Dijeli provjerite mogu li gosti danas slati sadržaj.",
    autoDeletionLabel: "Vrijeme do automatskog brisanja događaja",
    autoDeletionOverdue: "Vrijeme brisanja je prošlo — sljedeći posao uklonit će ovaj događaj.",
    autoDeletionFooterHint:
      "Prema razini paketa od datuma događaja. Promjena datuma ili paketa ažurira ovo. Ručno brisanje i dalje u Postavkama.",
    countdownJoin: ", ",
    countdownDayOne: "{n} dan",
    countdownDayMany: "{n} dana",
    countdownHourOne: "{n} sat",
    countdownHourMany: "{n} sati",
    countdownMinuteOne: "{n} minuta",
    countdownMinuteMany: "{n} minuta",
    countdownSubMinute: "Manje od minute",
    uploadWindowEnded: "Prozor za upload je završen — uploadi su zatvoreni.",
    statsTitle: "Statistika",
    statsPhotos: "Fotografije",
    statsVideos: "Videozapisi",
    statsGuests: "Gosti",
    accessCodeTitle: "Pristupni kod",
    copyCode: "Kopiraj kod",
    showQr: "Pokaži QR pozivnicu",
    hideQr: "Sakrij QR",
    scanHint: "Skeniraj za pridruživanje · ista veza kao u odjeljku Dijeli",
    openShareLink: "Otvori Dijeli za vezu i poruku →",
    recentPhotos: "Nedavne fotografije",
    noPhotosHint:
      "Još nema uploada. Otvorite galeriju za fotografije i videozapise kada stignu.",
    openGalleryBtn: "Na galeriju",
    viewGalleryFull: "Vidi punu galeriju →",
  },

  share: {
    heading: "Dijeli",
    subtitle: "Pošaljite vezu ili pristupni kod. Odaberite stil poruke zatim dijelite ili kopirajte.",
    messageStyleEyebrow: "Stil poruke",
    shareInvite: "Podijeli pozivnicu",
    shareFootnote:
      "Koristi zajedničko dijeljenje uređaja kad je dostupno; inače kopira punu poruku.",
    shareInviteDialogTitle: "Pozivnica",
    copyFailManual: "Nismo mogli kopirati — pokušajte tekst označiti ručno.",
    shareUnavailable:
      "Dijeljenje nije dostupno u ovom pregledniku. Umjesto toga kopirajte poruku ispod.",
    scanQr: "Skeniraj za ulaz",
    joinsSameHint: "Otvara istu pridruživanje stranicu kao gornja veza.",
    printPoster: "Isprintaj QR plakat",
    previewMessage: "Pregled poruke",
    copyFullMessage: "Kopiraj cijelu poruku",
    copyJoinLinkBtn: "Kopiraj vezu",
  },

  gallery: {
    loadFailed: "Učitavanje galerije nije uspjelo.",
    loading: "Učitavanje galerije…",
    deleteMediaFail: "Nismo mogli obrisati medij.",
    deleteTitle: "Obrisati ovaj upload?",
    deleteBody:
      "Uklanja stavku iz galerije i briše pohranu. Ovo se ne može poništiti.",
    title: "Galerija",
    subtitle: "Pregledaj poslane fotografije i videozapise",
    spotlightLabel: "Istaknuta fotografija",
    addMemory: "Dodaj uspomenu",
    addMemoryHint: "Dodirni za upload — ili ispusti datoteku ovdje",
    memoriesCount: "{count} uspomena",
    guestsCount: "{count} gostiju",
    filterAria: "Filtriraj vrstu medija",
    filterAll: "Sve",
    filterPhotos: "Fotografije",
    filterVideos: "Video",
    empty: "Još nema uploada.",
    loadMore: "Učitaj više…",
    lightboxAria: "Svjetlosni prikaz fotografije",
    closeLightboxAria: "Zatvori lightbox",
    downloadPhotoAria: "Preuzmi ovu fotografiju",
    downloadBtn: "Preuzmi",
    downloadWorking: "Preuzimanje…",
    downloadPhotoFail: "Nismo mogli preuzeti fotografiju.",
    downloadFailedWithStatus: "Preuzimanje nije uspjelo ({status}).",
    deleteBusy: "…",
    emptyGuest: "Još nema medija — budite prvi koji će uploadati!",
    openPhotoAria: "Otvori fotografiju preko cijelog ekrana",
    uploadedByYouAria: "Tvoj upload",
    zipExportCardEyebrow: "Primarni organizator",
    zipExportTitle: "ZIP skupni izvoz",
    zipExportBlurb:
      "Preuzmi medije galerije u jednom ZIP‑u. Pripremamo u pozadini i šaljemo e‑mail kad bude spremno. Poveznice istječu nakon 24 sata.",
    zipExportPrepare: "Pripremi ZIP",
    zipExportModalTitle: "Pripremi ZIP galerije",
    zipExportModalBody:
      "Fotografije su uključene po zadanom. Uključi opciju ispod za videozapise (veća datoteka, duže trajanje).",
    zipExportIncludeVideos: "Uključi videozapise",
    zipExportStart: "Pokreni izvoz",
    zipExportQueued: "U redu čekanja — javljamo kad bude spremno.",
    zipExportRunning: "Gradimo ZIP…",
    zipExportReady: "Spremno za preuzimanje",
    zipExportFailed: "Izvoz nije uspio",
    zipExportExpired: "Preuzimanje je isteklo",
    zipExportDownload: "Preuzmi ZIP",
    zipExportErrorGeneric: "Nismo mogli pokrenuti izvoz.",
    zipExportErrorPending: "Drugi izvoz je već u tijeku.",
    zipExportErrorQueue:
      "Nismo mogli pročitati red izvoza. Ako koristiš vlastiti Supabase projekt, primijeni najnovije migracije (uključujući `media_zip_exports`). Inače pokušaj ponovo za trenutak.",
    zipExportErrorTooMany: "Previše stavki za jedan ZIP. Ukloni neke uploadove ili izvezi bez videozapisa.",
  },

  guests: {
    title: "Gosti",
    loadFailed: "Učitavanje gosti nije uspjelo.",
    configureSupabase:
      "Postavite NEXT_PUBLIC_SUPABASE_URL i NEXT_PUBLIC_SUPABASE_ANON_KEY u `.env.local` za administraciju događaja.",
    cannotRemoveOrganizer: "Primarnog organizatora ne možete ukloniti.",
    rolesOnlyPrimary: "Samo primarni organizator može mijenjati uloge.",
    notAllowed: "Nije dopušteno.",
    memberNotFound: "Član nije pronađen.",
    actionFailed: "Radnja nije uspjela.",
    removeMemberFail: "Nismo mogli ukloniti člana.",
    updateRoleFail: "Nismo mogli promijeniti ulogu.",
    removeDialogTitle: "Ukloniti ovog člana?",
    removeDialogBody:
      "Izgubit će pristup događaju i galeriji. Poslani mediji ostaju osim ako ih ne obrišete iz galerije.",
    loadingGuests: "Učitavanje gosti…",
    empty: "Još se nitko nije pridružio.",
    youBadge: "(vi)",
    uploadsLine: "Prijenosi: {photos} fotografija • {videos} videozapisa",
    promoteCo: "Postavi kao suorganizatora",
    demoteGuest: "Postavi kao gosta",
    guestLabelFallback: "Gost",
    organizerLabelFallback: "Organizator",
    membersOne: "1 član",
    membersMany: "{n} članova",
  },

  supabase: {
    missingTitle: "Supabase nije konfiguriran",
    settingsBody:
      "Postavite NEXT_PUBLIC_SUPABASE_URL i NEXT_PUBLIC_SUPABASE_ANON_KEY u `.env.local` za uređivanje postavki događaja.",
    galleryBody:
      "Postavite NEXT_PUBLIC_SUPABASE_URL i NEXT_PUBLIC_SUPABASE_ANON_KEY u `.env.local` za učitavanje galerije.",
  },

  settingsPage: {
    title: "Postavke",
    eventsLink: "Događaji",
  },

  settingsClient: {
    profileEyebrow: "Profil",
    signedInAs: "Prijavljeni kao ",
    anon: "—",
    appearanceEyebrow: "Izgled",
    languageEyebrow: "Jezik",
    langEnglish: "Engleski",
    langHrvatski: "Hrvatski",
    langDeutsch: "Njemački",
    themeDarkLabel: "Tamno",
    themeLightLabel: "Svijetlo",
    appliesNote: "Primjenjuje se na stranice koje podržavaju svijetli i tamni način.",
    signOut: "Odjavi se",
    backEvents: "← Natrag na događaje",
    uploadNameEyebrow: "Prijenosi i galerija",
    uploadNameLabel: "Ime uz vaše prijenose",
    uploadNameHint:
      "Prikazuje se uz fotografije i video koje dodate u galeriji događaja. Koristi profil; nakon spremanja osvježite galeriju.",
    uploadNamePlaceholder: "npr. Ana",
    saveUploadName: "Spremi ime",
    uploadNameSaved: "Spremljeno.",
    uploadNameSaveFail: "Spremanje nije uspjelo. Pokušajte ponovno.",
    uploadNameNotSignedIn: "Niste prijavljeni.",
  },

  settingsTab: {
    heading: "Postavke",
    subtitle:
      "Ovaj kart vidi samo vi (primarni organizator) – ažurirajte kako se ovaj događaj pojavljuje u Calisto.",
    sectionNameIcon: "Naziv i ikona",
    eventNameLabel: "Naziv događaja",
    namePlaceholder: "npr. Ana i Marko",
    iconEyebrow: "Ikona događaja",
    chooseEmoji: "Odaberite emoji",
    closePicker: "Zatvori izbornik",
    noIcon: "Bez ikone",
    emojiAria: "Odabrani emoji",
    emojiPickerAria: "Emoji izbornik",
    iconHint:
      "Vidi se pokraj naslova u zaglavlju. Bez ikone koristi se zadani prikaz u navigaciji.",
    saveChanges: "Spremi promjene",
    reset: "Poništi",
    sectionSchedule: "Detalji događaja",
    scheduleNoteLead: "Spremljeno kao ",
    scheduleNoteTrail:
      "(kalendar). Promjena datuma ili paketa mijenja prozor za goste i kapacitet medija ovog događaja.",
    eventDateUtc: "Datum događaja (UTC kalendarski dan)",
    planTier: "Razine paketa",
    saveSchedule: "Spremi datum i plan",
    joinCodeEyebrow: "Kod za goste",
    dashboardBack: "Natrag na nadzornu ploču",
    dangerEyebrow: "Opasna zona",
    deletePhraseWord: "DELETE",
    confirmMismatch:
      "Potvrda ne odgovara. Unesite točno naslov pohranjenog događaja ili upišite DELETE.",
    deleteStorageIncomplete:
      "Događaj je uklonjen, ali neke datoteke u pohrani možda nisu obrisane. Kontaktirajte podršku.",
    deleteFail: "Nismo mogli obrisati događaj.",
    genericSaveFail: "Nismo mogli spremiti promjene.",
    validDateNeeded: "Odaberite važeći datum događaja.",
    scheduleSaveFail: "Nismo mogli ažurirati datum ili plan.",
    deleteTitleForever: "Trajno obrisati događaj?",
    deleteDialogBody:
      "Svi gube pristup odmah. Gosti, galerija, uploadi, kodovi – sve nestaje.",
    deleteConfirmLabel: "Da, obriši trajno",
    deleteDangerNote: "Trajanje brisanje se ne može poništiti.",
    deleteInstructionLead: "Potvrdite tako da upišete točan pohranjeni naslov ",
    deleteInstructionTrail: " ili riječ ",
    deleteConfirmPhraseLabel: "Potvrda",
    deletePlaceholderTitleOrWord: "Naslov ili DELETE",
    deleteButton: "Potpuno obriši događaj",
    exactParen: "(točno)",
  },

  validateCreate: {
    nameRequired:
      "Naziv događaja je obavezan. Vratite se i unesite ime.",
  },

  createStep1: {
    eyebrow: "Novi događaj",
    title: "Stvori događaj",
    description: "Automatski ćete postati organizator.",
    eventTitleLabel: "Naslov događaja",
    namePlaceholder: "npr. Ana i Marko",
    eventIconEyebrow: "Ikona događaja",
    eventDateLabel: "Datum događaja",
    continuePlan: "Nastavi na odabir plana →",
    searchEmojiHint: "Pretražite ili pregledajte sve emotikone. Pojavljuje se u zaglavlju događaja.",
    noEmojiBtn: "Bez emotikona",
    defaultEmojiAria: "Odabrani emoji",
  },

  createStep2: {
    eyebrow: "Korak 2 od 3",
    heading: "Odaberite paket",
    description: "Odaberite paket koji odgovara veličini događaja.",
    priceEyebrow: "Cijena",
    sale: "Akcija",
    popularBadge: "Popularno",
    unlimited: "Neograničeno",
    guestsPhotosVideos:
      "{guests} gostiju • {photos} fotografija • {videos} videozapisa",
    uploadsOpenAfterDays:
      "Upload je otvoren {n} dan(a) nakon datuma događaja",
    moreDetailsAria: "Više o paketu {plan}",
    detailRegionAria: "Detalji paketa {plan}",
    rowGuests: "Gosti",
    rowPhotos: "Fotografije",
    rowVideos: "Videozapisi",
    rowUploadWindow: "Prozor uploada",
    uploadWindowDays: "{n} dana",
    tipChangePlanLater: "Savjet: paket možete promijeniti kasnije u postavkama događaja.",
    continuePayment: "Nastavi na plaćanje →",
    payWord: "plaćanja",
    planWord: "paketa",
    dayWord: "dan",
    daysWord: "dana",
  },

  createStep3: {
    validationBack: "Natrag na detalje",
    checkingSession: "Provjera prijave…",
    needAuthHeading: "Prijavite se da završite događaj",
    needAuthBody:
      "Za dovršetak trebate račun. Nacrt ostaje za nastavak.",
    logInBtn: "Prijava",
    createAcctBtn: "Registracija",
    checkoutFailGeneric: "Nismo mogli započeti naplatu.",
    createFail: "Nismo mogli stvoriti događaj.",
    stepEyebrow: "Korak 3 · Pregled i stvaranje",
    confirmHeading: "Potvrda događaja",
    confirmBodyLeadBeforeName: "Upravo stvarate ",
    confirmBodyBetweenNameDate: " na ",
    confirmBodyTierWord: " uz paket ",
    confirmBodyPlanSuffix: "",
    confirmBodyPaidTail:
      " Plaćanje potvrđujete sigurno putem Stripea, zatim se događaj otvara uz limite paketa.",
    confirmBodyFreeTier:
      "Besplatna razina je potvrđena ovdje bez naplate — odmah pozovite goste.",
    selectedPlanEyebrow: "Odabrani paket",
    saleBadge: "Akcija",
    priceNotePaid: "U cijeni je PDV ako vrijedi — naplata jednokratno kod potvrde u Stripeu.",
    priceNoteFree: "Besplatni paket ostaje besplatan.",
    footnotePaid: "Prijeći ćete na Stripe za plaćanje; kad uspije, događaj je otvoren.",
    footnoteFree: "Bez naplate — album i kod za goste odmah su aktivni.",
    btnOpeningCheckout: "Otvaranje Stripea…",
    btnCreating: "Stvaranje…",
    btnStripe: "Nastavi na Stripe",
    btnConfirmFree: "Potvrdi i stvori događaj",
  },

  stripeComplete: {
    missingSession: "Nedostaje sesija naplate.",
    fulfillFailGeneric: "Završetak naplate nije uspio.",
    fulfillRetryHint: 'Ako je plaćanje upravo završeno, pričekajte malo pa pritisnite „Pokušaj ponovo”.',
    noEventId: "Plaćanje je završeno, ali identifikator događaja nije preuzet.",
    tryAgain: "Pokušaj ponovo",
    goDashboard: "Na nadzornu ploču",
    finalizing: "Dovršavamo plaćanje i stvaramo događaj…",
  },

  onboardingForm: {
    welcomeEyebrow: "Dobrodošli",
    title: "Recite nam o svojem događaju",
    subtitle: "Personalizuje vaše okruženje. Prvi događaj možete stvoriti iz nadzorne ploče.",
    kindEyebrow: "Što planirate?",
    displayNameLabel: "Kako vas zvati? (neobavezno)",
    namePlaceholderShort: "npr. Lara",
    choosePlanning: "Odaberite što planirate.",
    saveFail: "Spremanje nije uspjelo. Pokušajte ponovo.",
    notSignedIn: "Niste prijavljeni.",
    continueDashboard: "Nastavi na nadzornu ploču",
  },

  onboardingKinds: {
    wedding: "Vjenčanje",
    birthday: "Rođendan",
    corporate: "Poslovni",
    other: "Nešto drugo",
  },

  planTiersPage: {
    eyebrow: "Paketi",
    title: "Razine paketa",
    subtitle: "Brzi pregled limita gostiju i uploada.",
    back: "Natrag",
    uploadBadge: "{n} dana uploada",
    colGuests: "Gosti",
    colPhotos: "Fotografije",
    colVideos: "Videozapisi",
  },

  print: {
    deniedTitle: "Događaj nije pronađen",
    deniedDeny: "Nemate pristup ovom događaju.",
    backDashboard: "← Nadzorna ploča",
    backShare: "← Natrag na Dijeli",
    print: "Print",
    heroEyebrow: "Skeniraj za upload fotografija i videozapisa",
    footerGoToLead: "Ili otvori ",
    footerGoToTrail: " i unesi kod:",
    sheetHelper:
      "Dva ista kartica za stol po listu. Zareži duž isprekidane linije i stavi jednu karticu na svaki stol.",
    cutHere: "Zareži ovdje",
    paperSectionLabel: "Veličina papira",
    paperA4: "A4",
    paperLetter: "US Letter",
    templateSectionLabel: "Izgled",
    templateTableMinimal: "Jednostavno",
    templateTableBold: "Naglašeno",
    templateWeddingInviteSimple: "Vjenčanje · jednostavno",
    templateWeddingInviteFloral: "Vjenčanje · cvijetno",
    templateWeddingInviteBlueFloral: "Vjenčanje · plavo-cvijetno",
    templateWeddingInviteGeometric: "Vjenčanje · geometrijsko",
    templateWeddingInviteWatercolorCoast: "Vjenčanje · akvarel obala",
    templateWeddingInviteNavyBotanical: "Vjenčanje · mornarsko-botaničko",
    templateWeddingInviteGrayscaleGlitter: "Vjenčanje · sivo-zlatno",
    templateWeddingInviteTerraPill: "Vjenčanje · terakota-floralno",
    templateWeddingInviteGoldArchFloral: "Vjenčanje · zlatni luk",
    templateWeddingInviteCherryBlossom: "Vjenčanje · trešnjev cvijet",
    templateWeddingInviteOliveGoldFrame: "Vjenčanje · maslina i zlato",
    inviteTogetherWithOurFamilies: "ZAJEDNO S NAŠIM OBITELJIMA",
    inviteHonorUniteMarriage:
      "srdačno vas pozivamo da nam učinite čast svojim prisustvom dok u braku ujedinjujemo naše živote",
    inviteGlitterCordiallyLine: "srdačno ste pozvani na",
    inviteGlitterWeddingOfLine: "vjenčanje",
    inviteGlitterTogetherFamilies: "Zajedno s obiteljima",
    inviteGlitterCordiallyInviteCaps: "srdačno vas pozivaju na svoje",
    inviteGlitterWeddingWord: "Vjenčanje",
    inviteGlitterOn: "u",
    inviteTerraPleaseJoinUsFor: "Srdačno Vas pozivamo na",
    inviteWatercolorPleaseJoinUs: "Molimo vas da nam se pridružite",
    inviteWatercolorForCeremony: "na našem vjenčanju",
    inviteTerraTheWeddingOf: "naše vjenčanje",
    inviteGoldArchHeadline: "Srdačno Vas pozivamo na vjenčanje",
    inviteCherryPreambleStart: "srdačno ste",
    inviteCherryPreambleScript: "pozvani",
    inviteCherryPreambleMid: "na",
    inviteCherryPreambleEnd: "vjenčanje",
    inviteOliveWithLove: "s ljubavlju",
    inviteOliveCordiallyLine1: "srdačno Vas pozivamo",
    inviteOliveCordiallyLine2: "na svetu obred vjenčanja",
    inviteCategoryLabel: "Pozivnice",
    tableCategoryLabel: "Kartice za stol",
    inviteTogetherWithFamilies: "ZAJEDNO S OBITELJIMA",
    inviteCelebrationOn: "POZIVAJU VAS NA SVOJE VJENČANJE",
    inviteReceptionFollow: "Nastavlja se svečanom večerom",
    inviteWithJoyYouAre: "s radošću pozivaju",
    inviteInvitedToWeddingOf: "na vjenčanje",
    inviteAnd: "i",
    inviteDetailsGathering: "Skup",
    inviteDetailsChurch: "Ceremonija",
    inviteDetailsDinner: "Svečani prijem",
    sheetHelperInvitation: "Pregled pozivnice u uspravnom formatu. Veličina papira i dalje vrijedi pri ispisu.",
    backPrints: "← Natrag na Ispise",
    invitationUnavailableTitle: "Ovaj raspored nije dostupan",
    invitationUnavailable: "Ovaj raspored pozivnice nije dostupan za ovu vrstu događaja.",
    posterLanguageLabel: "Jezik na plakatu",
  },

  languagePicker: {
    label: "Jezik",
    locales: {
      en: "Engleski",
      hr: "Hrvatski",
      de: "Njemački",
    },
  },
};
