import type { AppUiDict } from "./en";

export const APP_UI_HR: AppUiDict = {
  defaults: {
    eventTitle: "Događaj",
    organizer: "Organizator",
    guest: "Gost",
  },

  theme: {
    light: "svijetla",
    dark: "tamna",
  },

  common: {
    cancel: "Odustani",
    delete: "Obriši",
    remove: "Ukloni",
    refresh: "Osvježi",
    copied: "Kopirano!",
    loading: "Učitavanje…",
    working: "Radi se…",
    back: "← Natrag",
    stay: "Ostani",
    pending: "Na čekanju",
    errorFallback: "Greška",
    configuringSupabase: "Konfiguriraj Supabase za pregled uploada.",
    loadCountsHint: "Konfiguriraj Supabase za učitavanje stalnih statistika.",
  },

  quotas: {
    unlimitedPlan: "Neograničen plan",
    ofCount: "od {n}",
    notOnPlan: "Razina nije u ovom paketu",
  },

  plans: {
    free: "Besplatno",
    standard: "Standard",
    plus: "Plus",
    premium: "Premium",
    max: "Max",
  },

  invites: {
    code: "Pristupni kod",
    link: "Poveznica za pridruživanje",
    introShort: "Pridružite nam se na događaju:",
    introFriendly: "Pozvani ste na",
    introFormal: "Uz sve poštovanje pozvani ste na",
    ctaShort: "Vidimo se!",
    ctaFriendly: "Jedva čekamo slaviti s vama!",
    ctaFormal: "Za nas bi bila čast vaša prisutnost.",
    templateShort: "Kratko",
    templateFriendly: "Prijateljski",
    templateFormal: "Formalno",
  },

  shell: {
    brand: "Calisto",
    navHome: "Početna",
    navSettings: "Postavke",
    joinCta: "Pridruži se",
    newEventAria: "Novi događaj",
    newEventShort: "+",
    newEventLabel: "+ Novi događaj",
    eventBreadcrumb: "← Početna",
    eventContext: "Događaj",
  },

  accountMenu: {
    triggerSr: "Izbornik računa",
    panelAria: "Račun",
    signedInLabel: "Prijavljeni ste",
    profile: "Profil",
    settings: "Postavke",
    help: "Pomoć",
    themeLabel: "Tema",
    signingOut: "Odjava…",
    signOut: "Odjavi se",
  },

  dashboard: {
    eyebrow: "Nadzorna ploča",
    helloTemplate: "Zdravo, {name}",
    fallbackName: "gost",
    subtitle: "Događaji koje organizirate ili na kojima ste suorganizator.",
    joinWithCode: "Pridruži se kodom",
    createEvent: "+ Stvori događaj",
    yourEvents: "Vaši događaji",
    memberOne: "član",
    membersMany: "članova",
    roleOrganizer: "Organizator",
    roleCoOrganizer: "Suorganizator",
    emptyHint: "Stvorite novi događaj ili se pridružite postojećem kodom od organizatora.",
    moreHint: "Stvorite još jedan događaj ili se pridružite kodom od organizatora.",
  },

  joinEntryFooter: {
    howItWorks: "Kako Calisto radi",
    home: "Početna",
  },

  joinForm: {
    title: "Pridružite se događaju",
    subtitle: "Unesite pristupni kod koji je podijelio organizator.",
    accessCodeLabel: "Pristupni kod",
    hintFormats: "Savjet: kodovi izgledaju kao ",
    joinCta: "Pridruži se događaju →",
    codeTooShort: "Unesite kod s pozivnice (najmanje 4 znaka).",
    notFound: "Nismo pronašli događaj za taj kod. Provjerite i pokušajte ponovo.",
    genericError: "Nešto je pošlo po zlu pri provjeri koda. Pokušajte ponovo.",
    previewEyebrow: "Pregled događaja",
    codePrefix: "Kod:",
    datePrefix: "Datum:",
    haveAccount: "Imam račun",
    guestContinue: "Nastavi kao gost",
    changeCode: "Promijeni kod",
  },

  globals: {
    errorTitle: "Nešto je pošlo po zlu",
    errorBody:
      "Dogodila se neočekivana greška. Možete pokušati ponovo ili se vratiti na početnu stranicu.",
    tryAgain: "Pokušaj ponovo",
    home: "Početna",
    notFoundCode: "404",
    notFoundTitle: "Stranica nije pronađena",
    notFoundBody: "Poveznica može biti kriva ili je stranica premještena.",
    calistoHome: "Calisto početna",
    welcomeLink: "Dobro došli",
  },

  guestJoin: {
    loading: "Učitavanje…",
    joining: "Pridruživanje događaju…",
    tagline: "Podijelite uspomene s ovog događaja.",
    uploadClosedBanner:
      "Upload je zatvoren za ovaj događaj (period uploada je završio). I dalje možete pregledavati galeriju.",
    sectionUpload: "Upload",
    sectionGallery: "Galerija",
    joinInvalidOrNotFound: "Taj kod trenutačno ne vrijedi za pridruživanje.",
    joinAlreadyMember: "Već ste dio ovog događaja.",
    joinGeneric: "Nešto je pošlo po zlu pri pridruživanju. Pokušajte osvježiti stranicu.",
  },

  welcomeModal: {
    eyebrow: "Pozvani ste",
    body: "Pridružite se za upload fotografija i videozapisa te pregled galerije.",
    createAccount: "Stvori račun",
    logIn: "Prijava",
    continueGuest: "Nastavi kao gost",
    nicknameLabel: "Vaš nadimak",
    nicknameError: "Nadimak mora imati između 2 i 30 znakova.",
    supabaseMissing: "Supabase nije konfiguriran. Pokušajte ponovo kasnije.",
    enterGuest: "Uđi kao gost",
    genericError: "Nešto je pošlo po zlu. Pokušajte ponovo.",
  },

  upload: {
    closedEvent: "Upload je zatvoren za ovaj događaj.",
    quotaReached: "Ovaj je događaj dosegao granicu za fotografije ili videozapise.",
    needSignIn: "Prijavite se za upload.",
    wrongType: "Podržane su samo slike i videozapisi.",
    failedGeneric: "Upload nije uspio.",
    dropPrompt: "Povuci i ispusti fotografije ili videozapise ovdje",
    tapBrowse: "ili dodirnite za pregled datoteka",
    uploading: "Upload…",
  },

  leaveRpc: {
    primaryOrganizer:
      "Primarni organizator tako ne može napustiti događaj — umjesto toga ga obrišite u Postavkama.",
    notMember: "Više niste član ovog događaja.",
    notAuth: "Ponovno se prijavite za nastavak.",
    fallback: "Nismo mogli napustiti ovaj događaj.",
  },

  leave: {
    title: "Napustiti događaj?",
    organizerMessage:
      "Izgubit ćete pristup uploadu i dijeljenju za ovaj događaj. Fotografije i videi koje ste već uploadali ostaju u galeriji za ostale.",
    guestMessage:
      "Izgubit ćete pristup ovom albumu i uploadu. Sve što ste već poslali ostaje u galeriji za druge goste.",
    confirm: "Napusti događaj",
    genericError: "Nismo mogli napustiti ovaj događaj.",
    ctaOrganizerTab: "Napusti događaj",
    guestCtaSame: "Napusti događaj",
    cancelStay: "Ostani",
  },

  auth: {
    oauthFail: "Google prijava se nije dovršila. Pokušajte ponovo ili koristite e‑poštu i lozinku.",
    googleStartFail: "Nismo mogli pokrenuti Google prijavu. Pokušajte uskoro ponovo.",
    checkEmailVerify: "Provjerite e‑poštu za potvrdu računa",
    welcomeEyebrow: "Dobrodošli u",
    brandRest: ".",
    continueGoogle: "Nastavi s Googleom",
    dividerOr: "Ili",
    dividerBody: "nastavi s e‑poštom",
    email: "E‑pošta",
    password: "Lozinka",
    signInSubmit: "Prijava",
    forgotPw: "Zaboravili ste lozinku?",
    fullName: "Puno ime",
    createAccountSubmit: "Registracija",
    emailPlaceholderRegister: "vi@primjer.com",
    emailPlaceholderAlt: "vi@primjer.com",
    passwordDots: "••••••••",
    namePlaceholder: "Antonio Horvat",
    legalPrefix: "Nastavljanjem prihvaćate Calisto",
    terms: "Uvjeti",
    privacy: "Pravila privatnosti",
    and: "i",
  },

  authRail: {
    aria: "Odaberite prijavu ili registraciju",
    loginKicker: "Dobrodošli natrag",
    loginLabel: "Prijava",
    registerKicker: "Novi ste na Calistu?",
    registerLabel: "Registracija",
  },

  forbidden: {
    title: "Događaj nije pronađen",
    deny: "Nemate pristup ovom događaju.",
    dashboardLink: "← Nadzorna ploča",
  },

  eventNav: {
    tabOverview: "Pregled",
    tabGuests: "Gosti",
    tabGallery: "Galerija",
    tabShare: "Dijeli",
    tabSettings: "Postavke",
    subtitle: "Podijelite s gostima da se mogu pridružiti.",
    tabsAria: "Odjeljci događaja",
  },

  overview: {
    yourRole: "Vaša uloga",
    uploadCloseLabel: "Preostalo vrijeme do zatvaranja uploada",
    uploadCloseShareHint: "U Dijeli provjerite mogu li gosti danas slati sadržaj.",
    autoDeletionLabel: "Vrijeme do automatskog brisanja događaja",
    autoDeletionOverdue: "Vrijeme brisanja je prošlo — sljedeći posao uklonit će ovaj događaj.",
    autoDeletionFooterHint:
      "Prema razini paketa od datuma događaja. Promjena datuma ili paketa ažurira ovo. Ručno brisanje i dalje u Postavkama.",
    countdownJoin: ", ",
    countdownDayOne: "{n} dan",
    countdownDayMany: "{n} dana",
    countdownHourOne: "{n} sat",
    countdownHourMany: "{n} sati",
    countdownMinuteOne: "{n} minuta",
    countdownMinuteMany: "{n} minuta",
    countdownSubMinute: "Manje od minute",
    uploadWindowEnded: "Prozor za upload je završen — uploadi su zatvoreni.",
    statsTitle: "Statistika",
    statsPhotos: "Fotografije",
    statsVideos: "Videozapisi",
    statsGuests: "Gosti",
    accessCodeTitle: "Pristupni kod",
    copyCode: "Kopiraj kod",
    showQr: "Pokaži QR pozivnicu",
    hideQr: "Sakrij QR",
    scanHint: "Skeniraj za pridruživanje · ista veza kao u odjeljku Dijeli",
    openShareLink: "Otvori Dijeli za vezu i poruku →",
    recentPhotos: "Nedavne fotografije",
    noPhotosHint:
      "Još nema uploada. Otvorite galeriju za fotografije i videozapise kada stignu.",
    openGalleryBtn: "Na galeriju",
    viewGalleryFull: "Vidi punu galeriju →",
  },

  share: {
    heading: "Dijeli",
    subtitle: "Pošaljite vezu ili pristupni kod. Odaberite stil poruke zatim dijelite ili kopirajte.",
    messageStyleEyebrow: "Stil poruke",
    shareInvite: "Podijeli pozivnicu",
    shareFootnote:
      "Koristi zajedničko dijeljenje uređaja kad je dostupno; inače kopira punu poruku.",
    shareInviteDialogTitle: "Pozivnica",
    copyFailManual: "Nismo mogli kopirati — pokušajte tekst označiti ručno.",
    shareUnavailable:
      "Dijeljenje nije dostupno u ovom pregledniku. Umjesto toga kopirajte poruku ispod.",
    scanQr: "Skeniraj za ulaz",
    joinsSameHint: "Otvara istu pridruživanje stranicu kao gornja veza.",
    printPoster: "Isprintaj QR plakat",
    previewMessage: "Pregled poruke",
    copyFullMessage: "Kopiraj cijelu poruku",
    copyJoinLinkBtn: "Kopiraj vezu",
  },

  gallery: {
    loadFailed: "Učitavanje galerije nije uspjelo.",
    loading: "Učitavanje galerije…",
    deleteMediaFail: "Nismo mogli obrisati medij.",
    deleteTitle: "Obrisati ovaj upload?",
    deleteBody:
      "Uklanja stavku iz galerije i briše pohranu. Ovo se ne može poništiti.",
    title: "Galerija",
    subtitle: "Pregledaj poslane fotografije i videozapise",
    filterAria: "Filtriraj vrstu medija",
    filterAll: "Sve",
    filterPhotos: "Fotografije",
    filterVideos: "Video",
    empty: "Još nema uploada.",
    loadMore: "Učitaj više…",
    lightboxAria: "Svjetlosni prikaz fotografije",
    closeLightboxAria: "Zatvori lightbox",
    downloadPhotoAria: "Preuzmi ovu fotografiju",
    downloadBtn: "Preuzmi",
    downloadWorking: "Preuzimanje…",
    downloadPhotoFail: "Nismo mogli preuzeti fotografiju.",
    downloadFailedWithStatus: "Preuzimanje nije uspjelo ({status}).",
    deleteBusy: "…",
    zipExportCardEyebrow: "Primarni organizator",
    zipExportTitle: "ZIP skupni izvoz",
    zipExportBlurb:
      "Preuzmi medije galerije u jednom ZIP‑u. Pripremamo u pozadini i šaljemo e‑mail kad bude spremno. Poveznice istječu nakon 24 sata.",
    zipExportPrepare: "Pripremi ZIP",
    zipExportModalTitle: "Pripremi ZIP galerije",
    zipExportModalBody:
      "Fotografije su uključene po zadanom. Uključi opciju ispod za videozapise (veća datoteka, duže trajanje).",
    zipExportIncludeVideos: "Uključi videozapise",
    zipExportStart: "Pokreni izvoz",
    zipExportQueued: "U redu čekanja — javljamo kad bude spremno.",
    zipExportRunning: "Gradimo ZIP…",
    zipExportReady: "Spremno za preuzimanje",
    zipExportFailed: "Izvoz nije uspio",
    zipExportExpired: "Preuzimanje je isteklo",
    zipExportDownload: "Preuzmi ZIP",
    zipExportErrorGeneric: "Nismo mogli pokrenuti izvoz.",
    zipExportErrorPending: "Drugi izvoz je već u tijeku.",
    zipExportErrorTooMany: "Previše stavki za jedan ZIP. Ukloni neke uploadove ili izvezi bez videozapisa.",
  },

  guests: {
    title: "Gosti",
    loadFailed: "Učitavanje gosti nije uspjelo.",
    configureSupabase:
      "Postavite NEXT_PUBLIC_SUPABASE_URL i NEXT_PUBLIC_SUPABASE_ANON_KEY u `.env.local` za administraciju događaja.",
    cannotRemoveOrganizer: "Primarnog organizatora ne možete ukloniti.",
    rolesOnlyPrimary: "Samo primarni organizator može mijenjati uloge.",
    notAllowed: "Nije dopušteno.",
    memberNotFound: "Član nije pronađen.",
    actionFailed: "Radnja nije uspjela.",
    removeMemberFail: "Nismo mogli ukloniti člana.",
    updateRoleFail: "Nismo mogli promijeniti ulogu.",
    removeDialogTitle: "Ukloniti ovog člana?",
    removeDialogBody:
      "Izgubit će pristup događaju i galeriji. Poslani mediji ostaju osim ako ih ne obrišete iz galerije.",
    loadingGuests: "Učitavanje gosti…",
    empty: "Još se nitko nije pridružio.",
    youBadge: "(vi)",
    uploadsLine: "Prijenosi: {photos} fotografija • {videos} videozapisa",
    promoteCo: "Postavi kao suorganizatora",
    demoteGuest: "Postavi kao gosta",
    guestLabelFallback: "Gost",
    organizerLabelFallback: "Organizator",
    membersOne: "1 član",
    membersMany: "{n} članova",
  },

  supabase: {
    missingTitle: "Supabase nije konfiguriran",
    settingsBody:
      "Postavite NEXT_PUBLIC_SUPABASE_URL i NEXT_PUBLIC_SUPABASE_ANON_KEY u `.env.local` za uređivanje postavki događaja.",
    galleryBody:
      "Postavite NEXT_PUBLIC_SUPABASE_URL i NEXT_PUBLIC_SUPABASE_ANON_KEY u `.env.local` za učitavanje galerije.",
  },

  settingsPage: {
    title: "Postavke",
    eventsLink: "Događaji",
  },

  settingsClient: {
    profileEyebrow: "Profil",
    signedInAs: "Prijavljeni kao ",
    anon: "—",
    appearanceEyebrow: "Izgled",
    languageEyebrow: "Jezik",
    langEnglish: "Engleski",
    langHrvatski: "Hrvatski",
    langDeutsch: "Njemački",
    themeDarkLabel: "Tamno",
    themeLightLabel: "Svijetlo",
    appliesNote: "Primjenjuje se na stranice koje podržavaju svijetli i tamni način.",
    signOut: "Odjavi se",
    backEvents: "← Natrag na događaje",
    uploadNameEyebrow: "Prijenosi i galerija",
    uploadNameLabel: "Ime uz vaše prijenose",
    uploadNameHint:
      "Prikazuje se uz fotografije i video koje dodate u galeriji događaja. Koristi profil; nakon spremanja osvježite galeriju.",
    uploadNamePlaceholder: "npr. Ana",
    saveUploadName: "Spremi ime",
    uploadNameSaved: "Spremljeno.",
    uploadNameSaveFail: "Spremanje nije uspjelo. Pokušajte ponovno.",
    uploadNameNotSignedIn: "Niste prijavljeni.",
  },

  settingsTab: {
    heading: "Postavke",
    subtitle:
      "Ovaj kart vidi samo vi (primarni organizator) – ažurirajte kako se ovaj događaj pojavljuje u Calisto.",
    sectionNameIcon: "Naziv i ikona",
    eventNameLabel: "Naziv događaja",
    namePlaceholder: "npr. Ana i Marko",
    iconEyebrow: "Ikona događaja",
    chooseEmoji: "Odaberite emoji",
    closePicker: "Zatvori izbornik",
    noIcon: "Bez ikone",
    emojiAria: "Odabrani emoji",
    emojiPickerAria: "Emoji izbornik",
    iconHint:
      "Vidi se pokraj naslova u zaglavlju. Bez ikone koristi se zadani prikaz u navigaciji.",
    saveChanges: "Spremi promjene",
    reset: "Poništi",
    sectionSchedule: "Detalji događaja",
    scheduleNoteLead: "Spremljeno kao ",
    scheduleNoteTrail:
      "(kalendar). Promjena datuma ili paketa mijenja prozor za goste i kapacitet medija ovog događaja.",
    eventDateUtc: "Datum događaja (UTC kalendarski dan)",
    planTier: "Razine paketa",
    saveSchedule: "Spremi datum i plan",
    joinCodeEyebrow: "Kod za goste",
    dashboardBack: "Natrag na nadzornu ploču",
    dangerEyebrow: "Opasna zona",
    deletePhraseWord: "DELETE",
    confirmMismatch:
      "Potvrda ne odgovara. Unesite točno naslov pohranjenog događaja ili upišite DELETE.",
    deleteStorageIncomplete:
      "Događaj je uklonjen, ali neke datoteke u pohrani možda nisu obrisane. Kontaktirajte podršku.",
    deleteFail: "Nismo mogli obrisati događaj.",
    genericSaveFail: "Nismo mogli spremiti promjene.",
    validDateNeeded: "Odaberite važeći datum događaja.",
    scheduleSaveFail: "Nismo mogli ažurirati datum ili plan.",
    deleteTitleForever: "Trajno obrisati događaj?",
    deleteDialogBody:
      "Svi gube pristup odmah. Gosti, galerija, uploadi, kodovi – sve nestaje.",
    deleteConfirmLabel: "Da, obriši trajno",
    deleteDangerNote: "Trajanje brisanje se ne može poništiti.",
    deleteInstructionLead: "Potvrdite tako da upišete točan pohranjeni naslov ",
    deleteInstructionTrail: " ili riječ ",
    deleteConfirmPhraseLabel: "Potvrda",
    deletePlaceholderTitleOrWord: "Naslov ili DELETE",
    deleteButton: "Potpuno obriši događaj",
    exactParen: "(točno)",
  },

  validateCreate: {
    nameRequired:
      "Naziv događaja je obavezan. Vratite se i unesite ime.",
  },

  createStep1: {
    eyebrow: "Novi događaj",
    title: "Stvori događaj",
    description: "Automatski ćete postati organizator.",
    eventTitleLabel: "Naslov događaja",
    namePlaceholder: "npr. Ana i Marko",
    eventIconEyebrow: "Ikona događaja",
    eventDateLabel: "Datum događaja",
    continuePlan: "Nastavi na odabir plana →",
    searchEmojiHint: "Pretražite ili pregledajte sve emotikone. Pojavljuje se u zaglavlju događaja.",
    noEmojiBtn: "Bez emotikona",
    defaultEmojiAria: "Odabrani emoji",
  },

  createStep2: {
    eyebrow: "Korak 2 od 3",
    heading: "Odaberite paket",
    description: "Odaberite paket koji odgovara veličini događaja.",
    priceEyebrow: "Cijena",
    sale: "Akcija",
    popularBadge: "Popularno",
    unlimited: "Neograničeno",
    guestsPhotosVideos:
      "{guests} gostiju • {photos} fotografija • {videos} videozapisa",
    uploadsOpenAfterDays:
      "Upload je otvoren {n} dan(a) nakon datuma događaja",
    moreDetailsAria: "Više o paketu {plan}",
    detailRegionAria: "Detalji paketa {plan}",
    rowGuests: "Gosti",
    rowPhotos: "Fotografije",
    rowVideos: "Videozapisi",
    rowUploadWindow: "Prozor uploada",
    uploadWindowDays: "{n} dana",
    tipChangePlanLater: "Savjet: paket možete promijeniti kasnije u postavkama događaja.",
    continuePayment: "Nastavi na plaćanje →",
    payWord: "plaćanja",
    planWord: "paketa",
    dayWord: "dan",
    daysWord: "dana",
  },

  createStep3: {
    validationBack: "Natrag na detalje",
    checkingSession: "Provjera prijave…",
    needAuthHeading: "Prijavite se da završite događaj",
    needAuthBody:
      "Za dovršetak trebate račun. Nacrt ostaje za nastavak.",
    logInBtn: "Prijava",
    createAcctBtn: "Registracija",
    checkoutFailGeneric: "Nismo mogli započeti naplatu.",
    createFail: "Nismo mogli stvoriti događaj.",
    stepEyebrow: "Korak 3 · Pregled i stvaranje",
    confirmHeading: "Potvrda događaja",
    confirmBodyLeadBeforeName: "Upravo stvarate ",
    confirmBodyBetweenNameDate: " na ",
    confirmBodyTierWord: " uz paket ",
    confirmBodyPlanSuffix: "",
    confirmBodyPaidTail:
      " Plaćanje potvrđujete sigurno putem Stripea, zatim se događaj otvara uz limite paketa.",
    confirmBodyFreeTier:
      "Besplatna razina je potvrđena ovdje bez naplate — odmah pozovite goste.",
    selectedPlanEyebrow: "Odabrani paket",
    saleBadge: "Akcija",
    priceNotePaid: "U cijeni je PDV ako vrijedi — naplata jednokratno kod potvrde u Stripeu.",
    priceNoteFree: "Besplatni paket ostaje besplatan.",
    footnotePaid: "Prijeći ćete na Stripe za plaćanje; kad uspije, događaj je otvoren.",
    footnoteFree: "Bez naplate — album i kod za goste odmah su aktivni.",
    btnOpeningCheckout: "Otvaranje Stripea…",
    btnCreating: "Stvaranje…",
    btnStripe: "Nastavi na Stripe",
    btnConfirmFree: "Potvrdi i stvori događaj",
  },

  stripeComplete: {
    missingSession: "Nedostaje sesija naplate.",
    fulfillFailGeneric: "Završetak naplate nije uspio.",
    fulfillRetryHint: 'Ako je plaćanje upravo završeno, pričekajte malo pa pritisnite „Pokušaj ponovo”.',
    noEventId: "Plaćanje je završeno, ali identifikator događaja nije preuzet.",
    tryAgain: "Pokušaj ponovo",
    goDashboard: "Na nadzornu ploču",
    finalizing: "Dovršavamo plaćanje i stvaramo događaj…",
  },

  onboardingForm: {
    welcomeEyebrow: "Dobrodošli",
    title: "Recite nam o svojem događaju",
    subtitle: "Personalizuje vaše okruženje. Prvi događaj možete stvoriti iz nadzorne ploče.",
    kindEyebrow: "Što planirate?",
    displayNameLabel: "Kako vas zvati? (neobavezno)",
    namePlaceholderShort: "npr. Lara",
    choosePlanning: "Odaberite što planirate.",
    saveFail: "Spremanje nije uspjelo. Pokušajte ponovo.",
    notSignedIn: "Niste prijavljeni.",
    continueDashboard: "Nastavi na nadzornu ploču",
  },

  onboardingKinds: {
    wedding: "Vjenčanje",
    birthday: "Rođendan",
    corporate: "Poslovni",
    other: "Nešto drugo",
  },

  planTiersPage: {
    eyebrow: "Paketi",
    title: "Razine paketa",
    subtitle: "Brzi pregled limita gostiju i uploada.",
    back: "Natrag",
    uploadBadge: "{n} dana uploada",
    colGuests: "Gosti",
    colPhotos: "Fotografije",
    colVideos: "Videozapisi",
  },

  print: {
    deniedTitle: "Događaj nije pronađen",
    deniedDeny: "Nemate pristup ovom događaju.",
    backDashboard: "← Nadzorna ploča",
    backShare: "← Natrag na Dijeli",
    print: "Print",
    heroEyebrow: "Skeniraj za upload fotografija i videozapisa",
    footerGoToLead: "Ili otvori ",
    footerGoToTrail: " i unesi kod:",
    sheetHelper:
      "Dva ista kartica za stol po listu. Zareži duž isprekidane linije i stavi jednu karticu na svaki stol.",
    cutHere: "Zareži ovdje",
    paperSectionLabel: "Veličina papira",
    paperA4: "A4",
    paperLetter: "US Letter",
    templateSectionLabel: "Izgled",
    templateTableMinimal: "Jednostavno",
    templateTableBold: "Naglašeno",
  },

  languagePicker: {
    label: "Jezik",
    locales: {
      en: "Engleski",
      hr: "Hrvatski",
      de: "Njemački",
    },
  },
};
